/*
 *FixGUITest.java
 *4/3/2014
 *@authod Adam Horrigan, x13735825.
 */
package worldcupapp;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FixGUITest extends javax.swing.JFrame {

    FixReadFile r = new FixReadFile("fixtures.txt"); //Create an instance of FixReadFile
    ArrayList<String> listOfLines = new ArrayList<>(); //Declare and create an ArrayList called listOfLines.

    /**
     * Creates new form GUITest
     */
    public FixGUITest() throws IOException {

        listOfLines = r.OpenFile(); // Assign List of Lines to OpenFile method
        initComponents();
        getContentPane().setBackground(new Color(255,255,0));
        this.setLocationRelativeTo(null); //Open window in center of screen.

    }

    public void foo() { //Method to read file into an ArrayList.
        String file_name = "test.txt";

        try {
            FixReadFile file = new FixReadFile(file_name);

            listOfLines = file.OpenFile();

        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

    }

    //this method closes the previous JPanel and opens a new JPanel
    //found at http://www.youtube.com/watch?v=Q2itkhLHaeE
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeft = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblNews = new javax.swing.JLabel();
        lblFixtures = new javax.swing.JLabel();
        lblMultimedia = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        butABC = new javax.swing.JButton();
        butDEF = new javax.swing.JButton();
        butGH = new javax.swing.JButton();
        butSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        panelLeft.setBackground(new java.awt.Color(51, 51, 51));
        panelLeft.setForeground(new java.awt.Color(51, 51, 51));
        panelLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.home.empty.png"))); // NOI18N
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        panelLeft.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 50));

        lblNews.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.newspaper.png"))); // NOI18N
        lblNews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewsMouseClicked(evt);
            }
        });
        panelLeft.add(lblNews, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 50));

        lblFixtures.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.sport.football.png"))); // NOI18N
        lblFixtures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFixturesMouseClicked(evt);
            }
        });
        panelLeft.add(lblFixtures, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 40));

        lblMultimedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.video.gallery.png"))); // NOI18N
        lblMultimedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMultimediaMouseClicked(evt);
            }
        });
        panelLeft.add(lblMultimedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 60));

        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.settings.png"))); // NOI18N
        lblSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingsMouseClicked(evt);
            }
        });
        panelLeft.add(lblSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 70, 50));

        getContentPane().add(panelLeft);
        panelLeft.setBounds(-1, -1, 100, 770);

        butABC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/ABC.png"))); // NOI18N
        butABC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butABCActionPerformed(evt);
            }
        });
        getContentPane().add(butABC);
        butABC.setBounds(200, 80, 180, 230);

        butDEF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/DEF.png"))); // NOI18N
        butDEF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDEFActionPerformed(evt);
            }
        });
        getContentPane().add(butDEF);
        butDEF.setBounds(470, 80, 180, 230);

        butGH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/GH.png"))); // NOI18N
        butGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGHActionPerformed(evt);
            }
        });
        getContentPane().add(butGH);
        butGH.setBounds(740, 80, 180, 230);

        butSearch.setText("Click here to search for a teams fixtures.");
        butSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSearchActionPerformed(evt);
            }
        });
        getContentPane().add(butSearch);
        butSearch.setBounds(410, 380, 300, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butABCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butABCActionPerformed
        // TODO add your handling code here:
        FixGroupABC ABC = null;
        try {
            ABC = new FixGroupABC();
        } catch (IOException ex) {
            Logger.getLogger(FixGUITest.class.getName()).log(Level.SEVERE, null, ex);
        }
        ABC.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_butABCActionPerformed

    private void butDEFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDEFActionPerformed
        // TODO add your handling code here:
        FixGroupDEF DEF = null;
        try {
            DEF = new FixGroupDEF();
        } catch (IOException ex) {
            Logger.getLogger(FixGUITest.class.getName()).log(Level.SEVERE, null, ex);
        }
        DEF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_butDEFActionPerformed

    private void butGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGHActionPerformed
        // TODO add your handling code here:
        FixGroupGH GH = null;
        try {
            GH = new FixGroupGH();
        } catch (IOException ex) {
            Logger.getLogger(FixGUITest.class.getName()).log(Level.SEVERE, null, ex);
        }
        GH.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_butGHActionPerformed

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        // TODO add your handling code here:
        MasterMenu MM = new MasterMenu();
        MM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblNewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewsMouseClicked
        // TODO add your handling code here:
        NewsMenu NM = new NewsMenu();
        NM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblNewsMouseClicked

    private void lblFixturesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFixturesMouseClicked
        // TODO add your handling code here:
        FixGUITest GT = null;
        try {
            GT = new FixGUITest();
        } catch (IOException ex) {
            Logger.getLogger(FixGUITest.class.getName()).log(Level.SEVERE, null, ex);
        }
        GT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblFixturesMouseClicked

    private void lblMultimediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMultimediaMouseClicked
        // TODO add your handling code here:
        MmMultimediaGUI MMGUI = new MmMultimediaGUI();
        MMGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblMultimediaMouseClicked

    private void lblSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseClicked
        // TODO add your handling code here:
        UserSettings SetUS = new UserSettings();
        SetUS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblSettingsMouseClicked

    private void butSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSearchActionPerformed
        // TODO add your handling code here:
        boolean x; //Boolean allows JOpationPane error message to be printed once if Input isn't found in listOfLines, rather than for everytime it isn't found.
        String choice = null;
        do { //Do - While to avoid reuse of the for loop with the if(!x) conditional.
        String Input = JOptionPane.showInputDialog("Please enter the team, which fixtures you want to see.");
        x = false;
        for (int i = 0; i < listOfLines.size(); i++) {
            if (listOfLines.get(i).toString().toLowerCase().contains(Input.toLowerCase())) { //Allow upercase and lowercase as .Contains() can't be used with .equalsIgnoreCase.
                JOptionPane.showMessageDialog(null, "The fixtures are: " + listOfLines.get(i));
                x = true;
            }
        }
        if (!x) { //If outside loop to prevent error message being printed for every index of listOfLines that doesn't hold variable Input.
            JOptionPane.showMessageDialog(null, "That team is not participating in the 2014 FIFA World Cup.");
            choice = JOptionPane.showInputDialog("Would you like to seach again? (Yes/No.)");

        }
        
    } while (("yes".equalsIgnoreCase(choice)) && !x); 


    }//GEN-LAST:event_butSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FixGUITest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FixGUITest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FixGUITest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FixGUITest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FixGUITest().setVisible(true);

                } catch (IOException ex) {
                    Logger.getLogger(FixGUITest.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butABC;
    private javax.swing.JButton butDEF;
    private javax.swing.JButton butGH;
    private javax.swing.JButton butSearch;
    private javax.swing.JLabel lblFixtures;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblMultimedia;
    private javax.swing.JLabel lblNews;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JPanel panelLeft;
    // End of variables declaration//GEN-END:variables
}
