/*
 *FixGroupGH.java
 *4/3/2014
 *@authod Adam Horrigan, x13735825.
 */
package worldcupapp;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;


public class FixGroupGH extends javax.swing.JFrame {

    FixReadFile r = new FixReadFile("fixtures.txt"); //Create an instance of FixReadFile
    FixDataTableModel theTableModel; // FixDataTableModel variable to hold theTableModel
    ArrayList<String> listOfLines = new ArrayList<>(); //Declare and create an ArrayList called listOfLines.

    /**
     * Creates new form table
     */
    public FixGroupGH() throws IOException {

        listOfLines = r.OpenFile(); // Assign List of Lines to OpenFile method.
        theTableModel = new FixDataTableModel(listOfLines); // Create an instance of the theTableModel and pass listOfLines into it.
        
        // initialise the form
        initComponents();
        getContentPane().setBackground(new Color(255,255,0));
        this.setLocationRelativeTo(null);

    }

    public void foo() { //Method to read file into an ArrayList.
        String file_name = "test.txt";

        try {
            FixReadFile file = new FixReadFile(file_name);

            listOfLines = file.OpenFile();

        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butgroupGH = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tabGroupG = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tabGroupH = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblGroupH = new javax.swing.JLabel();
        lblGroupG = new javax.swing.JLabel();
        panelLeft = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblNews = new javax.swing.JLabel();
        lblFixtures = new javax.swing.JLabel();
        lblMultimedia = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        radbutGermany = new javax.swing.JRadioButton();
        radbutPortugal = new javax.swing.JRadioButton();
        radbutGhana = new javax.swing.JRadioButton();
        radbutUSA = new javax.swing.JRadioButton();
        radbutBelgium = new javax.swing.JRadioButton();
        radbutAlgeria = new javax.swing.JRadioButton();
        radbutRussia = new javax.swing.JRadioButton();
        radbutKorea = new javax.swing.JRadioButton();
        lblPredict = new javax.swing.JLabel();
        lblGermany = new javax.swing.JLabel();
        lblPortugal = new javax.swing.JLabel();
        lblGhana = new javax.swing.JLabel();
        lblUsa = new javax.swing.JLabel();
        lblBelgium = new javax.swing.JLabel();
        lblAlgeria = new javax.swing.JLabel();
        lblRussia = new javax.swing.JLabel();
        lblKorea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jTable1.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {listOfLines.get(108), listOfLines.get(114), listOfLines.get(120)},
                {listOfLines.get(109), listOfLines.get(115), listOfLines.get(121)},
                {listOfLines.get(110), listOfLines.get(116), listOfLines.get(122)},
                {listOfLines.get(111), listOfLines.get(117), listOfLines.get(123)},
                {listOfLines.get(112), listOfLines.get(118), listOfLines.get(124)},
                {listOfLines.get(113), listOfLines.get(119), listOfLines.get(125)}
            },
            new String [] {
                "Date / Time", "Venue", "Match"
            }
        ));
        tabGroupG.setViewportView(jTable1);

        jTable2.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {listOfLines.get(126), listOfLines.get(132), listOfLines.get(138)},
                {listOfLines.get(127), listOfLines.get(133), listOfLines.get(139)},
                {listOfLines.get(128), listOfLines.get(134), listOfLines.get(140)},
                {listOfLines.get(129), listOfLines.get(135), listOfLines.get(141)},
                {listOfLines.get(130), listOfLines.get(136), listOfLines.get(142)},
                {listOfLines.get(131), listOfLines.get(137), listOfLines.get(143)}
            },
            new String [] {
                "Date / Time", "Venue", "Match"
            }
        ));
        tabGroupH.setViewportView(jTable2);

        lblGroupH.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblGroupH.setText("Group H");

        lblGroupG.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblGroupG.setText("Group G");

        panelLeft.setBackground(new java.awt.Color(51, 51, 51));
        panelLeft.setForeground(new java.awt.Color(51, 51, 51));
        panelLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.home.empty.png"))); // NOI18N
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        panelLeft.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 50));

        lblNews.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.newspaper.png"))); // NOI18N
        lblNews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewsMouseClicked(evt);
            }
        });
        panelLeft.add(lblNews, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 50));

        lblFixtures.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.sport.football.png"))); // NOI18N
        lblFixtures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFixturesMouseClicked(evt);
            }
        });
        panelLeft.add(lblFixtures, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 40));

        lblMultimedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.video.gallery.png"))); // NOI18N
        lblMultimedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMultimediaMouseClicked(evt);
            }
        });
        panelLeft.add(lblMultimedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 60));

        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.settings.png"))); // NOI18N
        lblSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingsMouseClicked(evt);
            }
        });
        panelLeft.add(lblSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 70, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabGroupH, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGroupG)
                    .addComponent(tabGroupG, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGroupH))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblGroupG)
                .addGap(18, 18, 18)
                .addComponent(tabGroupG, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGroupH)
                .addGap(18, 18, 18)
                .addComponent(tabGroupH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 703, 768);

        butgroupGH.add(radbutGermany);
        radbutGermany.setText("Germany");
        radbutGermany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbutGermanyActionPerformed(evt);
            }
        });
        getContentPane().add(radbutGermany);
        radbutGermany.setBounds(721, 80, 80, 23);

        butgroupGH.add(radbutPortugal);
        radbutPortugal.setText("Portugal");
        radbutPortugal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbutPortugalActionPerformed(evt);
            }
        });
        getContentPane().add(radbutPortugal);
        radbutPortugal.setBounds(816, 80, 90, 23);

        butgroupGH.add(radbutGhana);
        radbutGhana.setText("Ghana");
        radbutGhana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbutGhanaActionPerformed(evt);
            }
        });
        getContentPane().add(radbutGhana);
        radbutGhana.setBounds(721, 106, 70, 23);

        butgroupGH.add(radbutUSA);
        radbutUSA.setText("USA");
        radbutUSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbutUSAActionPerformed(evt);
            }
        });
        getContentPane().add(radbutUSA);
        radbutUSA.setBounds(816, 106, 70, 23);

        butgroupGH.add(radbutBelgium);
        radbutBelgium.setText("Belgium");
        radbutBelgium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbutBelgiumActionPerformed(evt);
            }
        });
        getContentPane().add(radbutBelgium);
        radbutBelgium.setBounds(721, 132, 80, 23);

        butgroupGH.add(radbutAlgeria);
        radbutAlgeria.setText("Algeria");
        radbutAlgeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbutAlgeriaActionPerformed(evt);
            }
        });
        getContentPane().add(radbutAlgeria);
        radbutAlgeria.setBounds(816, 132, 80, 23);

        butgroupGH.add(radbutRussia);
        radbutRussia.setText("Russia");
        radbutRussia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbutRussiaActionPerformed(evt);
            }
        });
        getContentPane().add(radbutRussia);
        radbutRussia.setBounds(721, 158, 80, 23);

        butgroupGH.add(radbutKorea);
        radbutKorea.setText("Korea Republic");
        radbutKorea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbutKoreaActionPerformed(evt);
            }
        });
        getContentPane().add(radbutKorea);
        radbutKorea.setBounds(816, 158, 110, 23);

        lblPredict.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblPredict.setText("Predicted line ups:");
        getContentPane().add(lblPredict);
        lblPredict.setBounds(721, 26, 139, 23);

        lblGermany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/germany.png"))); // NOI18N
        getContentPane().add(lblGermany);
        lblGermany.setBounds(710, 270, 270, 360);
        lblGermany.setVisible(false);

        lblPortugal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/portugal.png"))); // NOI18N
        getContentPane().add(lblPortugal);
        lblPortugal.setBounds(710, 270, 270, 360);
        lblPortugal.setVisible(false);

        lblGhana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/ghana.png"))); // NOI18N
        getContentPane().add(lblGhana);
        lblGhana.setBounds(710, 270, 270, 360);
        lblGhana.setVisible(false);

        lblUsa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/usa.png"))); // NOI18N
        getContentPane().add(lblUsa);
        lblUsa.setBounds(710, 270, 270, 360);
        lblUsa.setVisible(false);

        lblBelgium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/belgium.png"))); // NOI18N
        getContentPane().add(lblBelgium);
        lblBelgium.setBounds(710, 270, 270, 360);
        lblBelgium.setVisible(false);

        lblAlgeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/algeria.png"))); // NOI18N
        getContentPane().add(lblAlgeria);
        lblAlgeria.setBounds(710, 270, 270, 360);
        lblAlgeria.setVisible(false);

        lblRussia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/russia.png"))); // NOI18N
        getContentPane().add(lblRussia);
        lblRussia.setBounds(710, 270, 270, 360);
        lblRussia.setVisible(false);

        lblKorea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/korea.png"))); // NOI18N
        getContentPane().add(lblKorea);
        lblKorea.setBounds(710, 270, 270, 360);
        lblKorea.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radbutPortugalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbutPortugalActionPerformed
        // TODO add your handling code here:
        lblKorea.setVisible(false); //Switch between predicted teams.
        lblGermany.setVisible(false);
        lblGhana.setVisible(false);
        lblUsa.setVisible(false);
        lblBelgium.setVisible(false);
        lblAlgeria.setVisible(false);
        lblRussia.setVisible(false);
        lblPortugal.setVisible(true);
    }//GEN-LAST:event_radbutPortugalActionPerformed

    private void radbutGermanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbutGermanyActionPerformed
        // TODO add your handling code here:
        lblKorea.setVisible(false); //Switch between predicted teams.
        lblPortugal.setVisible(false);
        lblGhana.setVisible(false);
        lblUsa.setVisible(false);
        lblBelgium.setVisible(false);
        lblAlgeria.setVisible(false);
        lblRussia.setVisible(false);
        lblGermany.setVisible(true);
    }//GEN-LAST:event_radbutGermanyActionPerformed

    private void radbutGhanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbutGhanaActionPerformed
        // TODO add your handling code here:
        lblGermany.setVisible(false); //Switch between predicted teams.
        lblPortugal.setVisible(false);
        lblKorea.setVisible(false);
        lblUsa.setVisible(false);
        lblBelgium.setVisible(false);
        lblAlgeria.setVisible(false);
        lblRussia.setVisible(false);
        lblGhana.setVisible(true);
    }//GEN-LAST:event_radbutGhanaActionPerformed

    private void radbutUSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbutUSAActionPerformed
        // TODO add your handling code here:
        lblGermany.setVisible(false); //Switch between predicted teams.
        lblPortugal.setVisible(false);
        lblGhana.setVisible(false);
        lblKorea.setVisible(false);
        lblBelgium.setVisible(false);
        lblAlgeria.setVisible(false);
        lblRussia.setVisible(false);
        lblUsa.setVisible(true);
    }//GEN-LAST:event_radbutUSAActionPerformed

    private void radbutBelgiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbutBelgiumActionPerformed
        // TODO add your handling code here:
        lblGermany.setVisible(false); //Switch between predicted teams.
        lblPortugal.setVisible(false);
        lblGhana.setVisible(false);
        lblUsa.setVisible(false);
        lblKorea.setVisible(false);
        lblAlgeria.setVisible(false);
        lblRussia.setVisible(false);
        lblBelgium.setVisible(true);
    }//GEN-LAST:event_radbutBelgiumActionPerformed

    private void radbutAlgeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbutAlgeriaActionPerformed
        // TODO add your handling code here:
        lblGermany.setVisible(false); //Switch between predicted teams.
        lblPortugal.setVisible(false);
        lblGhana.setVisible(false);
        lblUsa.setVisible(false);
        lblBelgium.setVisible(false);
        lblKorea.setVisible(false);
        lblRussia.setVisible(false);
        lblAlgeria.setVisible(true);
    }//GEN-LAST:event_radbutAlgeriaActionPerformed

    private void radbutRussiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbutRussiaActionPerformed
        // TODO add your handling code here:
        lblGermany.setVisible(false); //Switch between predicted teams.
        lblPortugal.setVisible(false);
        lblGhana.setVisible(false);
        lblUsa.setVisible(false);
        lblBelgium.setVisible(false);
        lblAlgeria.setVisible(false);
        lblKorea.setVisible(false);
        lblRussia.setVisible(true);
    }//GEN-LAST:event_radbutRussiaActionPerformed

    private void radbutKoreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbutKoreaActionPerformed
        // TODO add your handling code here:
        lblGermany.setVisible(false); //Switch between predicted teams.
        lblPortugal.setVisible(false);
        lblGhana.setVisible(false);
        lblUsa.setVisible(false);
        lblBelgium.setVisible(false);
        lblAlgeria.setVisible(false);
        lblRussia.setVisible(false);
        lblKorea.setVisible(true);
    }//GEN-LAST:event_radbutKoreaActionPerformed

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        // TODO add your handling code here:
        MasterMenu MM = new MasterMenu();
        MM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblNewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewsMouseClicked
        // TODO add your handling code here:
        NewsMenu NM = new NewsMenu();
        NM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblNewsMouseClicked

    private void lblFixturesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFixturesMouseClicked
        // TODO add your handling code here:
        FixGUITest GT = null;
        try {
            GT = new FixGUITest();
        } catch (IOException ex) {
            Logger.getLogger(FixGroupGH.class.getName()).log(Level.SEVERE, null, ex);
        }
        GT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblFixturesMouseClicked

    private void lblMultimediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMultimediaMouseClicked
        // TODO add your handling code here:
        MmMultimediaGUI MMGUI = new MmMultimediaGUI();
        MMGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblMultimediaMouseClicked

    private void lblSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseClicked
        // TODO add your handling code here:
        UserSettings SetUS = new UserSettings();
        SetUS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblSettingsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FixGroupGH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FixGroupGH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FixGroupGH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FixGroupGH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FixGroupGH().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FixGroupGH.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup butgroupGH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblAlgeria;
    private javax.swing.JLabel lblBelgium;
    private javax.swing.JLabel lblFixtures;
    private javax.swing.JLabel lblGermany;
    private javax.swing.JLabel lblGhana;
    private javax.swing.JLabel lblGroupG;
    private javax.swing.JLabel lblGroupH;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblKorea;
    private javax.swing.JLabel lblMultimedia;
    private javax.swing.JLabel lblNews;
    private javax.swing.JLabel lblPortugal;
    private javax.swing.JLabel lblPredict;
    private javax.swing.JLabel lblRussia;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JLabel lblUsa;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JRadioButton radbutAlgeria;
    private javax.swing.JRadioButton radbutBelgium;
    private javax.swing.JRadioButton radbutGermany;
    private javax.swing.JRadioButton radbutGhana;
    private javax.swing.JRadioButton radbutKorea;
    private javax.swing.JRadioButton radbutPortugal;
    private javax.swing.JRadioButton radbutRussia;
    private javax.swing.JRadioButton radbutUSA;
    private javax.swing.JScrollPane tabGroupG;
    private javax.swing.JScrollPane tabGroupH;
    // End of variables declaration//GEN-END:variables
}
