package worldcupapp;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Anthony Bloomer
 */
public class MasterMenu extends javax.swing.JFrame {

    Date date = new Date();
    User u = new User();

    /**
     * Creates new form MasterMenu
     */
    public MasterMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.dateLbl.setText(date.toString());
        this.userInfo();
    }

    private void userInfo() {
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;

        File f = new File("current.data");

        if (!f.exists()) {
            try {
                inFile = new File("user.data");
                fStream = new FileInputStream(inFile);
                oStream = new ObjectInputStream(fStream);

                ArrayList<User> xList;
                xList = (ArrayList<User>) oStream.readObject();
                for (User x : xList) {
                    this.greetingLbl.setText("Welcome.");
                    this.favTeamLbl.setText(x.getTeam());
                    if (x.getTeam().equalsIgnoreCase("Ireland")) {
                        flagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/irish_flag.png")));
                    } else if (x.getTeam().equalsIgnoreCase("Brazil")) {
                        flagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/brazil_flag.png")));
                    } else if (x.getTeam().equalsIgnoreCase("Spain")) {
                        flagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/spain_flag.png")));
                    }
                }

                oStream.close();
            } catch (IOException | ClassNotFoundException e) {
                System.out.println(e);
            }
        } else {
            try {
                FileInputStream fis = new FileInputStream(f);
                ObjectInputStream ois = new ObjectInputStream(fis);

                ArrayList<CurrentUser> cList;
                cList = (ArrayList<CurrentUser>) ois.readObject();

                for (CurrentUser x : cList) {
                    this.greetingLbl.setText("Welcome.");
                    this.favTeamLbl.setText(x.getTeam());
                    if (x.getTeam().equalsIgnoreCase("Ireland")) {
                        flagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/irish_flag.png")));
                    } else if (x.getTeam().equalsIgnoreCase("Brazil")) {
                        flagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/brazil_flag.png")));
                    } else if (x.getTeam().equalsIgnoreCase("Spain")) {
                        flagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/spain_flag.png")));
                    }
                }

            } catch (IOException | ClassNotFoundException e) {
                System.out.println(e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greetingLbl = new javax.swing.JLabel();
        teamLbl = new javax.swing.JLabel();
        favTeamLbl = new javax.swing.JLabel();
        flagLbl = new javax.swing.JLabel();
        fixTileLbl = new javax.swing.JLabel();
        newsTileLbl = new javax.swing.JLabel();
        photoTileLbl = new javax.swing.JLabel();
        videoTileLbl = new javax.swing.JLabel();
        todayDateLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        abcLbl = new javax.swing.JLabel();
        defLbl = new javax.swing.JLabel();
        ghLbl = new javax.swing.JLabel();
        stLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        greetingLbl.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        greetingLbl.setText("Welcome");

        teamLbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        teamLbl.setText("Your Team:");

        favTeamLbl.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N

        flagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/user.png"))); // NOI18N

        fixTileLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/fixtures.png"))); // NOI18N
        fixTileLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fixTileLblMouseClicked(evt);
            }
        });

        newsTileLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/news.png"))); // NOI18N
        newsTileLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsTileLblMouseClicked(evt);
            }
        });

        photoTileLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/photo.png"))); // NOI18N
        photoTileLbl.setText("a");
        photoTileLbl.setPreferredSize(new java.awt.Dimension(250, 150));
        photoTileLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoTileLblMouseClicked(evt);
            }
        });

        videoTileLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/video.png"))); // NOI18N
        videoTileLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videoTileLblMouseClicked(evt);
            }
        });

        todayDateLbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        todayDateLbl.setText("Today's Date:");

        dateLbl.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N

        abcLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/groupABC.png"))); // NOI18N
        abcLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abcLblMouseClicked(evt);
            }
        });

        defLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/groupDEF.png"))); // NOI18N
        defLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defLblMouseClicked(evt);
            }
        });

        ghLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/groupGH.png"))); // NOI18N
        ghLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ghLblMouseClicked(evt);
            }
        });

        stLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/images/st.png"))); // NOI18N
        stLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(videoTileLbl)
                                .addGap(6, 6, 6)
                                .addComponent(photoTileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(268, 268, 268))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newsTileLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fixTileLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ghLbl)
                                    .addComponent(abcLbl))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stLbl)
                                    .addComponent(defLbl))
                                .addGap(6, 6, 6))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(flagLbl)
                                .addGap(12, 12, 12)
                                .addComponent(greetingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(todayDateLbl)
                                .addGap(10, 10, 10)
                                .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teamLbl)
                                .addGap(10, 10, 10)
                                .addComponent(favTeamLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flagLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greetingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(todayDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamLbl)
                    .addComponent(favTeamLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newsTileLbl)
                    .addComponent(fixTileLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(abcLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(defLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ghLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(videoTileLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(photoTileLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stLblMouseClicked
        // TODO add your handling code here:
        UserSettings us = new UserSettings();
        us.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stLblMouseClicked

    private void newsTileLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsTileLblMouseClicked
        // TODO add your handling code here:
        NewsMenu n = new NewsMenu();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newsTileLblMouseClicked

    private void fixTileLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fixTileLblMouseClicked
        FixGUITest g = null;
        try {
            g = new FixGUITest();
        } catch (IOException ex) {
            Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        g.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:

    }//GEN-LAST:event_fixTileLblMouseClicked

    private void abcLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abcLblMouseClicked
        FixGroupABC g = null;
        try {
            g = new FixGroupABC();
        } catch (IOException ex) {
            Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_abcLblMouseClicked

    private void videoTileLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoTileLblMouseClicked
        MmMultimediaGUI m = new MmMultimediaGUI();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_videoTileLblMouseClicked

    private void photoTileLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoTileLblMouseClicked
        // TODO add your handling code here:
        MmPhotoGUI p = new MmPhotoGUI();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_photoTileLblMouseClicked

    private void defLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defLblMouseClicked
        FixGroupDEF g = null;
        try {
            g = new FixGroupDEF();
        } catch (IOException ex) {
            Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        g.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_defLblMouseClicked

    private void ghLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ghLblMouseClicked
        FixGroupGH g = null;
        try {
            g = new FixGroupGH();
        } catch (IOException ex) {
            Logger.getLogger(MasterMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ghLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abcLbl;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel defLbl;
    private javax.swing.JLabel favTeamLbl;
    private javax.swing.JLabel fixTileLbl;
    private javax.swing.JLabel flagLbl;
    private javax.swing.JLabel ghLbl;
    private javax.swing.JLabel greetingLbl;
    private javax.swing.JLabel newsTileLbl;
    private javax.swing.JLabel photoTileLbl;
    private javax.swing.JLabel stLbl;
    private javax.swing.JLabel teamLbl;
    private javax.swing.JLabel todayDateLbl;
    private javax.swing.JLabel videoTileLbl;
    // End of variables declaration//GEN-END:variables
}
