/*
 Author Marius Vorosila x13419708
Ref:// Method of opening videous is based on
http://stackoverflow.com/questions/20440484/embed-a-youtube-video-to-jframe
this multimedia section is responsible to open and play videous,
also it allows user to rate highlights videous and watch the other rates
 */

package worldcupapp;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marius
 */
public class MmHighGUI extends javax.swing.JFrame {
    
    private ArrayList<MmHigh>rList;
    
     public int rate ;
     
  //declare array of rate objects
   //  MmHigh arr[];
     
  //declare count variable to keep track of how many objects are in array
    int count;  

    /**
     * Creates new form multimedia
     */
    public MmHighGUI() {
        rList = new ArrayList<>();
        initComponents();
         rate = 0;
         
   //create array of question objects
   //  arr = new MmHigh[100];
      
    //initialise count to 0
      
      count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSidebar = new javax.swing.JPanel();
        lbMenu = new javax.swing.JPanel();
        homeLbl = new javax.swing.JLabel();
        newsLbl = new javax.swing.JLabel();
        setLbl = new javax.swing.JLabel();
        fixLbl = new javax.swing.JLabel();
        mmLbl = new javax.swing.JLabel();
        lbBackground = new javax.swing.JPanel();
        lbDisplay = new javax.swing.JPanel();
        lbPlay = new javax.swing.JLabel();
        lbHigh1 = new javax.swing.JLabel();
        lbDisplay1 = new javax.swing.JPanel();
        lbPlay1 = new javax.swing.JLabel();
        lbHigh2 = new javax.swing.JLabel();
        lbRating = new javax.swing.JLabel();
        btRating = new javax.swing.JButton();
        RatingTf = new javax.swing.JTextField();
        btView = new javax.swing.JButton();
        lbDisplay2 = new javax.swing.JPanel();
        lbPlay2 = new javax.swing.JLabel();
        lbHigh3 = new javax.swing.JLabel();
        lbDisplay3 = new javax.swing.JPanel();
        lbPlay3 = new javax.swing.JLabel();
        lbHigh4 = new javax.swing.JLabel();
        lbDisplay4 = new javax.swing.JPanel();
        lbPlay4 = new javax.swing.JLabel();
        lbHigh5 = new javax.swing.JLabel();
        lbDisplay5 = new javax.swing.JPanel();
        lbPlay5 = new javax.swing.JLabel();
        lbHigh6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMenu.setBackground(new java.awt.Color(51, 51, 51));
        lbMenu.setPreferredSize(new java.awt.Dimension(105, 768));

        homeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.home.empty.png"))); // NOI18N
        homeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLblMouseClicked(evt);
            }
        });

        newsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.newspaper.png"))); // NOI18N
        newsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsLblMouseClicked(evt);
            }
        });

        setLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.settings.png"))); // NOI18N
        setLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setLblMouseClicked(evt);
            }
        });

        fixLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.sport.football.png"))); // NOI18N
        fixLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fixLblMouseClicked(evt);
            }
        });

        mmLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.video.gallery.png"))); // NOI18N
        mmLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lbMenuLayout = new javax.swing.GroupLayout(lbMenu);
        lbMenu.setLayout(lbMenuLayout);
        lbMenuLayout.setHorizontalGroup(
            lbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(lbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mmLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fixLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        lbMenuLayout.setVerticalGroup(
            lbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbMenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(newsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(fixLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(mmLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(setLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout lbSidebarLayout = new javax.swing.GroupLayout(lbSidebar);
        lbSidebar.setLayout(lbSidebarLayout);
        lbSidebarLayout.setHorizontalGroup(
            lbSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        lbSidebarLayout.setVerticalGroup(
            lbSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );

        lbBackground.setBackground(new java.awt.Color(255, 255, 0));

        lbDisplay.setBackground(new java.awt.Color(0, 153, 0));
        lbDisplay.setPreferredSize(new java.awt.Dimension(201, 196));

        lbPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/flame.png"))); // NOI18N
        lbPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlayMouseClicked(evt);
            }
        });

        lbHigh1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbHigh1.setForeground(new java.awt.Color(255, 255, 255));
        lbHigh1.setText("Highlights Vol.1");

        javax.swing.GroupLayout lbDisplayLayout = new javax.swing.GroupLayout(lbDisplay);
        lbDisplay.setLayout(lbDisplayLayout);
        lbDisplayLayout.setHorizontalGroup(
            lbDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplayLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(lbDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHigh1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPlay))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        lbDisplayLayout.setVerticalGroup(
            lbDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHigh1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbDisplay1.setBackground(new java.awt.Color(255, 51, 51));
        lbDisplay1.setPreferredSize(new java.awt.Dimension(201, 244));

        lbPlay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/flame.png"))); // NOI18N
        lbPlay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay1MouseClicked(evt);
            }
        });

        lbHigh2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbHigh2.setForeground(new java.awt.Color(255, 255, 255));
        lbHigh2.setText("Highlights Vol.2");

        javax.swing.GroupLayout lbDisplay1Layout = new javax.swing.GroupLayout(lbDisplay1);
        lbDisplay1.setLayout(lbDisplay1Layout);
        lbDisplay1Layout.setHorizontalGroup(
            lbDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(lbDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay1Layout.createSequentialGroup()
                        .addComponent(lbPlay1)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay1Layout.createSequentialGroup()
                        .addComponent(lbHigh2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        lbDisplay1Layout.setVerticalGroup(
            lbDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbHigh2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbRating.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbRating.setText("Rate This Week Highlights ( 0-10)");

        btRating.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        btRating.setText("RATE");
        btRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRatingActionPerformed(evt);
            }
        });

        RatingTf.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        RatingTf.setAlignmentX(5.0F);
        RatingTf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RatingTf.setMargin(new java.awt.Insets(20, 20, 20, 20));

        btView.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        btView.setText("View Ratings");
        btView.setPreferredSize(new java.awt.Dimension(140, 70));
        btView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewActionPerformed(evt);
            }
        });

        lbDisplay2.setBackground(new java.awt.Color(0, 0, 255));

        lbPlay2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/flame.png"))); // NOI18N
        lbPlay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay2MouseClicked(evt);
            }
        });

        lbHigh3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbHigh3.setForeground(new java.awt.Color(255, 255, 255));
        lbHigh3.setText("Highlights Vol.3");

        javax.swing.GroupLayout lbDisplay2Layout = new javax.swing.GroupLayout(lbDisplay2);
        lbDisplay2.setLayout(lbDisplay2Layout);
        lbDisplay2Layout.setHorizontalGroup(
            lbDisplay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(lbDisplay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay2Layout.createSequentialGroup()
                        .addComponent(lbPlay2)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay2Layout.createSequentialGroup()
                        .addComponent(lbHigh3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        lbDisplay2Layout.setVerticalGroup(
            lbDisplay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbHigh3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlay2)
                .addGap(19, 19, 19))
        );

        lbDisplay3.setBackground(new java.awt.Color(255, 51, 153));

        lbPlay3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/flame.png"))); // NOI18N
        lbPlay3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay3MouseClicked(evt);
            }
        });

        lbHigh4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbHigh4.setForeground(new java.awt.Color(255, 255, 255));
        lbHigh4.setText("Highlights Vol.4");

        javax.swing.GroupLayout lbDisplay3Layout = new javax.swing.GroupLayout(lbDisplay3);
        lbDisplay3.setLayout(lbDisplay3Layout);
        lbDisplay3Layout.setHorizontalGroup(
            lbDisplay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbPlay3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbHigh4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lbDisplay3Layout.setVerticalGroup(
            lbDisplay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHigh4, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(lbPlay3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbDisplay4.setBackground(new java.awt.Color(102, 102, 102));

        lbPlay4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/flame.png"))); // NOI18N
        lbPlay4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay4MouseClicked(evt);
            }
        });

        lbHigh5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbHigh5.setForeground(new java.awt.Color(255, 255, 255));
        lbHigh5.setText("Highlights Vol.5");

        javax.swing.GroupLayout lbDisplay4Layout = new javax.swing.GroupLayout(lbDisplay4);
        lbDisplay4.setLayout(lbDisplay4Layout);
        lbDisplay4Layout.setHorizontalGroup(
            lbDisplay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(lbDisplay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay4Layout.createSequentialGroup()
                        .addComponent(lbPlay4)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay4Layout.createSequentialGroup()
                        .addComponent(lbHigh5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        lbDisplay4Layout.setVerticalGroup(
            lbDisplay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHigh5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPlay4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lbDisplay5.setBackground(new java.awt.Color(0, 204, 204));

        lbPlay5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/flame.png"))); // NOI18N
        lbPlay5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay5MouseClicked(evt);
            }
        });
        lbPlay5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbPlay5KeyPressed(evt);
            }
        });

        lbHigh6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbHigh6.setForeground(new java.awt.Color(255, 255, 255));
        lbHigh6.setText("Highlights Vol.6");

        javax.swing.GroupLayout lbDisplay5Layout = new javax.swing.GroupLayout(lbDisplay5);
        lbDisplay5.setLayout(lbDisplay5Layout);
        lbDisplay5Layout.setHorizontalGroup(
            lbDisplay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lbDisplay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay5Layout.createSequentialGroup()
                        .addComponent(lbPlay5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay5Layout.createSequentialGroup()
                        .addComponent(lbHigh6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        lbDisplay5Layout.setVerticalGroup(
            lbDisplay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbHigh6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPlay5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout lbBackgroundLayout = new javax.swing.GroupLayout(lbBackground);
        lbBackground.setLayout(lbBackgroundLayout);
        lbBackgroundLayout.setHorizontalGroup(
            lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbBackgroundLayout.createSequentialGroup()
                .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbBackgroundLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btRating, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(RatingTf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(btView, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lbBackgroundLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbDisplay3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbDisplay1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDisplay4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbDisplay2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDisplay5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(lbBackgroundLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lbRating, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        lbBackgroundLayout.setVerticalGroup(
            lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbBackgroundLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDisplay5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDisplay3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDisplay4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(lbRating, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRating, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RatingTf, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1017, 834));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mmLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmLblMouseClicked
       // this method is opening the particular GUI , and hides the previous , eg if you are in section "highlights" and you click on "top 10" section
       // it will open "top 10 " and will hide "highlights;
        
        MmMultimediaGUI myMulti = new MmMultimediaGUI();
        myMulti.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mmLblMouseClicked

    private void fixLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fixLblMouseClicked
     
       FixGUITest myFix = null;
        try {
            myFix = new FixGUITest();
        } catch (IOException ex) {
            Logger.getLogger(MmHighGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       myFix.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_fixLblMouseClicked

    private void setLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setLblMouseClicked
   
       UserSettings u = new UserSettings();
       u.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_setLblMouseClicked

    private void newsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsLblMouseClicked
       
        NewsMenu myNews = new NewsMenu();
        myNews.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_newsLblMouseClicked

    private void homeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLblMouseClicked
       
        MasterMenu m = new MasterMenu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeLblMouseClicked

    private void lbPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayMouseClicked
       
        // Method is based on http://stackoverflow.com/questions/20440484/embed-a-youtube-video-to-jframe
        //This method is opening a file by using the defoult application eg "windows media player"
        
             File high1 = new File("src/worldcupapp/Vid/high1.mp4");
        try {
            Desktop.getDesktop().open(high1);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_lbPlayMouseClicked

    private void lbPlay1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay1MouseClicked
        
             File high2 = new File("src/worldcupapp/Vid/high2.mp4");
        try {
            Desktop.getDesktop().open(high2);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_lbPlay1MouseClicked

    private void btRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRatingActionPerformed
        // TODO add your handling code here:
        // Get text from TextFields
        rate = Integer.parseInt(RatingTf.getText());

        //create a new Question object

        MmHigh h = new MmHigh();

        //add contents of textfields to m
        h.SetRate(rate);

        //add m to array of Rate objects
        rList.add(h);

        //increase count to show that another object has been added to the array
        count++;

        //Creates file with all ratings
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String rate = RatingTf.getText();
        try {
            outFile = new File("ratingsHigh.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(rate);
            bw.newLine();

            bw.close();
            JOptionPane.showMessageDialog(null, "Thank you for rate our video");
        } catch (IOException e) {
            System.out.println("Error writing to file: " + e);
        }
    }//GEN-LAST:event_btRatingActionPerformed

    private void btViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewActionPerformed
     
        // Loop through array of objects 
        
        for(int i = 0 ; i<rList.size(); i++){
            MmHigh rate = new MmHigh();
            JOptionPane.showMessageDialog(null, "Your Rate  " +rList.get(i).getRate());
        }
        String Allrate;
        String rate;
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("ratingsHigh.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);
            Allrate = ("");

            rate = br.readLine();
            
            while (rate != null) {
                Allrate = Allrate+rate+",";
                rate = br.readLine();
            }
            
            JOptionPane.showMessageDialog(null, "All Rates: " + Allrate);
            br.close();
            
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btViewActionPerformed

    private void lbPlay2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay2MouseClicked
     
              File high1 = new File("src/worldcupapp/Vid/high3.mp4");
        try {
            Desktop.getDesktop().open(high1);
        } catch (IOException e) {
        }
        
    }//GEN-LAST:event_lbPlay2MouseClicked

    private void lbPlay3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay3MouseClicked
      
              File high1 = new File("src/worldcupapp/Vid/high4.mp4");
        try {
            Desktop.getDesktop().open(high1);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_lbPlay3MouseClicked

    private void lbPlay4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay4MouseClicked

              File high1 = new File("src/worldcupapp/Vid/high5.mp4");
        try {
            Desktop.getDesktop().open(high1);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_lbPlay4MouseClicked

    private void lbPlay5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbPlay5KeyPressed
    
    }//GEN-LAST:event_lbPlay5KeyPressed

    private void lbPlay5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay5MouseClicked

              File high1 = new File("src/worldcupapp/Vid/high6.mp4");
        try {
            Desktop.getDesktop().open(high1);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_lbPlay5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MmMultimediaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RatingTf;
    private javax.swing.JButton btRating;
    private javax.swing.JButton btView;
    private javax.swing.JLabel fixLbl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JPanel lbBackground;
    private javax.swing.JPanel lbDisplay;
    private javax.swing.JPanel lbDisplay1;
    private javax.swing.JPanel lbDisplay2;
    private javax.swing.JPanel lbDisplay3;
    private javax.swing.JPanel lbDisplay4;
    private javax.swing.JPanel lbDisplay5;
    private javax.swing.JLabel lbHigh1;
    private javax.swing.JLabel lbHigh2;
    private javax.swing.JLabel lbHigh3;
    private javax.swing.JLabel lbHigh4;
    private javax.swing.JLabel lbHigh5;
    private javax.swing.JLabel lbHigh6;
    private javax.swing.JPanel lbMenu;
    private javax.swing.JLabel lbPlay;
    private javax.swing.JLabel lbPlay1;
    private javax.swing.JLabel lbPlay2;
    private javax.swing.JLabel lbPlay3;
    private javax.swing.JLabel lbPlay4;
    private javax.swing.JLabel lbPlay5;
    private javax.swing.JLabel lbRating;
    private javax.swing.JPanel lbSidebar;
    private javax.swing.JLabel mmLbl;
    private javax.swing.JLabel newsLbl;
    private javax.swing.JLabel setLbl;
    // End of variables declaration//GEN-END:variables
}
