/*
 Author Marius Vorosila x13419708
Ref:// Method of opening videous is based on
http://stackoverflow.com/questions/20440484/embed-a-youtube-video-to-jframe
this multimedia section is responsible to open and play videous,
also it allows user to rate top10 videous and watch the other rates
 */

package worldcupapp;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Marius
 */
public class MmTop10GUI extends javax.swing.JFrame {
    
     private ArrayList<MmTop10> rList;
    
      public int rate ;
    
// //declare array of rate objects
   // MmTop10 arr[];
    
//declare count variable to keep track of how many objects are in array
    int count;

    /**
     * Creates new form multimedia
     */
    public MmTop10GUI() {
        rList = new ArrayList<>();
        initComponents();
        rate = 0;
        
         //create array of question objects
     // arr = new MmTop10[100];
      
      //initialise count to 0
      
      count = 0;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBody = new javax.swing.JPanel();
        lbMenu = new javax.swing.JPanel();
        homeLbl = new javax.swing.JLabel();
        newsLbl = new javax.swing.JLabel();
        setLbl = new javax.swing.JLabel();
        fixLbl = new javax.swing.JLabel();
        mmLbl = new javax.swing.JLabel();
        lbBackground = new javax.swing.JPanel();
        lbDisplay3 = new javax.swing.JPanel();
        lbPlay3 = new javax.swing.JLabel();
        lbTop4 = new javax.swing.JLabel();
        lbDisplay = new javax.swing.JPanel();
        lbPlay = new javax.swing.JLabel();
        lbTop1 = new javax.swing.JLabel();
        lbDisplay1 = new javax.swing.JPanel();
        lbPlay1 = new javax.swing.JLabel();
        lbTop2 = new javax.swing.JLabel();
        lbDisplay4 = new javax.swing.JPanel();
        lbPlay4 = new javax.swing.JLabel();
        lbTop5 = new javax.swing.JLabel();
        lbDisplay2 = new javax.swing.JPanel();
        lbPlay2 = new javax.swing.JLabel();
        lbTop3 = new javax.swing.JLabel();
        lbDisplay5 = new javax.swing.JPanel();
        lbPLay5 = new javax.swing.JLabel();
        lbTop6 = new javax.swing.JLabel();
        lbRating = new javax.swing.JLabel();
        btRating = new javax.swing.JButton();
        RatingTf = new javax.swing.JTextField();
        btView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMenu.setBackground(new java.awt.Color(51, 51, 51));
        lbMenu.setPreferredSize(new java.awt.Dimension(105, 768));

        homeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.home.empty.png"))); // NOI18N
        homeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLblMouseClicked(evt);
            }
        });

        newsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.newspaper.png"))); // NOI18N
        newsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsLblMouseClicked(evt);
            }
        });

        setLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.settings.png"))); // NOI18N
        setLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setLblMouseClicked(evt);
            }
        });

        fixLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.sport.football.png"))); // NOI18N
        fixLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fixLblMouseClicked(evt);
            }
        });

        mmLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.video.gallery.png"))); // NOI18N
        mmLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lbMenuLayout = new javax.swing.GroupLayout(lbMenu);
        lbMenu.setLayout(lbMenuLayout);
        lbMenuLayout.setHorizontalGroup(
            lbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(lbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mmLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fixLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        lbMenuLayout.setVerticalGroup(
            lbMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbMenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(newsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(fixLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(mmLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(setLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout lbBodyLayout = new javax.swing.GroupLayout(lbBody);
        lbBody.setLayout(lbBodyLayout);
        lbBodyLayout.setHorizontalGroup(
            lbBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        lbBodyLayout.setVerticalGroup(
            lbBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lbBackground.setBackground(new java.awt.Color(255, 255, 0));

        lbDisplay3.setBackground(new java.awt.Color(255, 153, 0));
        lbDisplay3.setPreferredSize(new java.awt.Dimension(201, 244));

        lbPlay3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/video.png"))); // NOI18N
        lbPlay3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay3MouseClicked(evt);
            }
        });

        lbTop4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbTop4.setForeground(new java.awt.Color(255, 255, 255));
        lbTop4.setText("Top 10  Vol.4");

        javax.swing.GroupLayout lbDisplay3Layout = new javax.swing.GroupLayout(lbDisplay3);
        lbDisplay3.setLayout(lbDisplay3Layout);
        lbDisplay3Layout.setHorizontalGroup(
            lbDisplay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(lbDisplay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay3Layout.createSequentialGroup()
                        .addComponent(lbPlay3)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay3Layout.createSequentialGroup()
                        .addComponent(lbTop4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        lbDisplay3Layout.setVerticalGroup(
            lbDisplay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTop4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlay3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        lbDisplay.setBackground(new java.awt.Color(102, 0, 153));
        lbDisplay.setPreferredSize(new java.awt.Dimension(201, 196));

        lbPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/video.png"))); // NOI18N
        lbPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlayMouseClicked(evt);
            }
        });

        lbTop1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbTop1.setForeground(new java.awt.Color(255, 255, 255));
        lbTop1.setText("Top 10  Vol.1");

        javax.swing.GroupLayout lbDisplayLayout = new javax.swing.GroupLayout(lbDisplay);
        lbDisplay.setLayout(lbDisplayLayout);
        lbDisplayLayout.setHorizontalGroup(
            lbDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplayLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbPlay)
                .addGap(35, 35, 35))
            .addGroup(lbDisplayLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbTop1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbDisplayLayout.setVerticalGroup(
            lbDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplayLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTop1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlay)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lbDisplay1.setBackground(new java.awt.Color(0, 153, 153));

        lbPlay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/video.png"))); // NOI18N
        lbPlay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay1MouseClicked(evt);
            }
        });

        lbTop2.setBackground(new java.awt.Color(255, 255, 255));
        lbTop2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbTop2.setForeground(new java.awt.Color(255, 255, 255));
        lbTop2.setText("Top 10  Vol.2");

        javax.swing.GroupLayout lbDisplay1Layout = new javax.swing.GroupLayout(lbDisplay1);
        lbDisplay1.setLayout(lbDisplay1Layout);
        lbDisplay1Layout.setHorizontalGroup(
            lbDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lbDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPlay1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay1Layout.createSequentialGroup()
                        .addComponent(lbTop2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(33, 33, 33))
        );
        lbDisplay1Layout.setVerticalGroup(
            lbDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTop2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        lbDisplay4.setBackground(new java.awt.Color(0, 102, 204));
        lbDisplay4.setPreferredSize(new java.awt.Dimension(201, 244));

        lbPlay4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/video.png"))); // NOI18N
        lbPlay4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay4MouseClicked(evt);
            }
        });

        lbTop5.setBackground(new java.awt.Color(255, 255, 255));
        lbTop5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbTop5.setForeground(new java.awt.Color(255, 255, 255));
        lbTop5.setText("Top 10  Vol.5");

        javax.swing.GroupLayout lbDisplay4Layout = new javax.swing.GroupLayout(lbDisplay4);
        lbDisplay4.setLayout(lbDisplay4Layout);
        lbDisplay4Layout.setHorizontalGroup(
            lbDisplay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(lbDisplay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPlay4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay4Layout.createSequentialGroup()
                        .addComponent(lbTop5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        lbDisplay4Layout.setVerticalGroup(
            lbDisplay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbTop5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPlay4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbDisplay2.setBackground(new java.awt.Color(0, 204, 51));

        lbPlay2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/video.png"))); // NOI18N
        lbPlay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay2MouseClicked(evt);
            }
        });

        lbTop3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbTop3.setForeground(new java.awt.Color(255, 255, 255));
        lbTop3.setText("Top 10   Vol.3");

        javax.swing.GroupLayout lbDisplay2Layout = new javax.swing.GroupLayout(lbDisplay2);
        lbDisplay2.setLayout(lbDisplay2Layout);
        lbDisplay2Layout.setHorizontalGroup(
            lbDisplay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(lbDisplay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPlay2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay2Layout.createSequentialGroup()
                        .addComponent(lbTop3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(34, 34, 34))
        );
        lbDisplay2Layout.setVerticalGroup(
            lbDisplay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTop3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlay2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        lbDisplay5.setBackground(new java.awt.Color(255, 0, 51));
        lbDisplay5.setPreferredSize(new java.awt.Dimension(201, 244));

        lbPLay5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/video.png"))); // NOI18N
        lbPLay5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPLay5MouseClicked(evt);
            }
        });

        lbTop6.setBackground(new java.awt.Color(255, 255, 255));
        lbTop6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbTop6.setForeground(new java.awt.Color(255, 255, 255));
        lbTop6.setText("Top 10  Vol.6");

        javax.swing.GroupLayout lbDisplay5Layout = new javax.swing.GroupLayout(lbDisplay5);
        lbDisplay5.setLayout(lbDisplay5Layout);
        lbDisplay5Layout.setHorizontalGroup(
            lbDisplay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay5Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(lbDisplay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay5Layout.createSequentialGroup()
                        .addComponent(lbPLay5)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay5Layout.createSequentialGroup()
                        .addComponent(lbTop6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        lbDisplay5Layout.setVerticalGroup(
            lbDisplay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTop6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPLay5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        lbRating.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbRating.setText("Rate This Week TOP10 ( 0-10)");

        btRating.setBackground(new java.awt.Color(255, 0, 51));
        btRating.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        btRating.setForeground(new java.awt.Color(255, 255, 255));
        btRating.setText("RATE");
        btRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRatingActionPerformed(evt);
            }
        });

        RatingTf.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        RatingTf.setAlignmentX(5.0F);
        RatingTf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RatingTf.setMargin(new java.awt.Insets(20, 20, 20, 20));

        btView.setBackground(new java.awt.Color(255, 0, 51));
        btView.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        btView.setForeground(new java.awt.Color(255, 255, 255));
        btView.setText("View Ratings");
        btView.setPreferredSize(new java.awt.Dimension(140, 70));
        btView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lbBackgroundLayout = new javax.swing.GroupLayout(lbBackground);
        lbBackground.setLayout(lbBackgroundLayout);
        lbBackgroundLayout.setHorizontalGroup(
            lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbBackgroundLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDisplay3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDisplay4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDisplay1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
            .addGroup(lbBackgroundLayout.createSequentialGroup()
                .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbBackgroundLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btRating, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(RatingTf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btView, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lbBackgroundLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(lbRating, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbBackgroundLayout.setVerticalGroup(
            lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbBackgroundLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDisplay4, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(lbDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(lbRating, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lbBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRating, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RatingTf, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1063, 806));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLblMouseClicked
    // this method is opening the particular GUI , and hides the previous , eg if you are in section "highlights" and you click on "top 10" section
    // it will open "top 10 " and will hide "highlights
        
        MasterMenu m = new MasterMenu();;
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeLblMouseClicked

    private void newsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsLblMouseClicked
        
        NewsMenu myNews = new NewsMenu();
        myNews.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newsLblMouseClicked

    private void setLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setLblMouseClicked
        
        UserSettings u = new UserSettings();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_setLblMouseClicked

    private void fixLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fixLblMouseClicked
        // TODO add your handling code here:
        FixGUITest myFix = null;
         try {
             myFix = new FixGUITest();
         } catch (IOException ex) {
             Logger.getLogger(MmTop10GUI.class.getName()).log(Level.SEVERE, null, ex);
         }
        myFix.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fixLblMouseClicked

    private void mmLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmLblMouseClicked
        
        MmMultimediaGUI myMulti = new MmMultimediaGUI();
        myMulti.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mmLblMouseClicked

    private void lbPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayMouseClicked
        
        
        // Method is based on http://stackoverflow.com/questions/20440484/embed-a-youtube-video-to-jframe
        //This method is opening a file by using the defoult application eg "windows media player
        
             File top1 = new File("src/worldcupapp/Vid/Top10#1.mp4");
        try {
            Desktop.getDesktop().open(top1);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_lbPlayMouseClicked

    private void lbPlay1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay1MouseClicked
       
              File top2 = new File("src/worldcupapp/Vid/Top10#2.mp4");
        try {
            Desktop.getDesktop().open(top2);
        } catch (IOException e) {
        }
        
    }//GEN-LAST:event_lbPlay1MouseClicked

    private void lbPlay2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay2MouseClicked
      
              File top3 = new File("src/worldcupapp/Vid/Top10#3.mp4");
        try {
            Desktop.getDesktop().open(top3);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_lbPlay2MouseClicked

    private void lbPlay3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay3MouseClicked
       
              File top4 = new File("src/worldcupapp/Vid/Top10#4.mp4");
        try {
            Desktop.getDesktop().open(top4);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_lbPlay3MouseClicked

    private void lbPlay4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay4MouseClicked
        
              File top5 = new File("src/worldcupapp/Vid/Top10#5.mp4");
        try {
            Desktop.getDesktop().open(top5);
        } catch (IOException e) {
        }
        
    }//GEN-LAST:event_lbPlay4MouseClicked

    private void lbPLay5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPLay5MouseClicked
       
              File top6 = new File("src/worldcupapp/Vid/Top10#6.mp4");
        try {
            Desktop.getDesktop().open(top6);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_lbPLay5MouseClicked

    private void btRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRatingActionPerformed
        // TODO add your handling code here:
        // Get text from TextFields
        rate = Integer.parseInt(RatingTf.getText());

        //create a new Question object

        MmTop10 t = new MmTop10();

        //add contents of textfields to m
        t.SetRate(rate);

        //add m to array of Rate objects
        rList.add(t);

        //increase count to show that another object has been added to the array
        count++;

        //Creates file with all ratings
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String rate = RatingTf.getText();
        try {
            outFile = new File("ratingsTop10.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(rate);
            bw.newLine();

            bw.close();
            JOptionPane.showMessageDialog(null, "Thank you for rate our video");
        } catch (IOException e) {
            System.out.println("Error writing to file: " + e);
        }
    }//GEN-LAST:event_btRatingActionPerformed

    private void btViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewActionPerformed
       
       // Loop through array of objects 
        
        for(int i = 0 ; i<rList.size(); i++){
            MmTop10 rate = new MmTop10();
            JOptionPane.showMessageDialog(null, "Your Rate  " +rList.get(i).getRate());
        }
        String Allrate;
        String rate;
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("ratingsTop10.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);
            Allrate = ("");

            rate = br.readLine();
            
            while (rate != null) {
                Allrate = Allrate+rate+",";
                rate = br.readLine();
            }
            
            JOptionPane.showMessageDialog(null, "All Rates: " + Allrate);
            br.close();
            
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MmMultimediaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RatingTf;
    private javax.swing.JButton btRating;
    private javax.swing.JButton btView;
    private javax.swing.JLabel fixLbl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JPanel lbBackground;
    private javax.swing.JPanel lbBody;
    private javax.swing.JPanel lbDisplay;
    private javax.swing.JPanel lbDisplay1;
    private javax.swing.JPanel lbDisplay2;
    private javax.swing.JPanel lbDisplay3;
    private javax.swing.JPanel lbDisplay4;
    private javax.swing.JPanel lbDisplay5;
    private javax.swing.JPanel lbMenu;
    private javax.swing.JLabel lbPLay5;
    private javax.swing.JLabel lbPlay;
    private javax.swing.JLabel lbPlay1;
    private javax.swing.JLabel lbPlay2;
    private javax.swing.JLabel lbPlay3;
    private javax.swing.JLabel lbPlay4;
    private javax.swing.JLabel lbRating;
    private javax.swing.JLabel lbTop1;
    private javax.swing.JLabel lbTop2;
    private javax.swing.JLabel lbTop3;
    private javax.swing.JLabel lbTop4;
    private javax.swing.JLabel lbTop5;
    private javax.swing.JLabel lbTop6;
    private javax.swing.JLabel mmLbl;
    private javax.swing.JLabel newsLbl;
    private javax.swing.JLabel setLbl;
    // End of variables declaration//GEN-END:variables
}
