/*
 Author Marius Vorosila x13419708
Ref:// Method of opening videous is based on
http://stackoverflow.com/questions/20440484/embed-a-youtube-video-to-jframe
this multimedia section is responsible to open and play videous,
also it allows user to rate videous and watch the other rates
 */

package worldcupapp;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class MmVideousGUI extends javax.swing.JFrame {
   
   private ArrayList<MmVideous> rList;
   
   public int rate ;
   
//declare count variable to keep track of how many objects are in array
    int count;
    
    /**
     * Creates new form multimedia
     */
    public MmVideousGUI() {
        initComponents();
        rList = new ArrayList<>();
        rate = 0;
        count = 0;//initialise count to 0
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBody = new javax.swing.JPanel();
        lbSideBar = new javax.swing.JPanel();
        homeLbl = new javax.swing.JLabel();
        newsLbl = new javax.swing.JLabel();
        setLbl = new javax.swing.JLabel();
        fixLbl = new javax.swing.JLabel();
        mmLbl = new javax.swing.JLabel();
        lbBackGround = new javax.swing.JPanel();
        lbDisplay = new javax.swing.JPanel();
        lbPlay = new javax.swing.JLabel();
        lbWelcome = new javax.swing.JLabel();
        lbDisplay1 = new javax.swing.JPanel();
        lbPlay2 = new javax.swing.JLabel();
        lbNeymar = new javax.swing.JLabel();
        lbDisplay2 = new javax.swing.JPanel();
        lbParty = new javax.swing.JLabel();
        lbPlay3 = new javax.swing.JLabel();
        lbDisplay3 = new javax.swing.JPanel();
        lbPlay4 = new javax.swing.JLabel();
        lbWinner = new javax.swing.JLabel();
        lbDisplay4 = new javax.swing.JPanel();
        lbPlay5 = new javax.swing.JLabel();
        lbSkills = new javax.swing.JLabel();
        lbDisplay5 = new javax.swing.JPanel();
        lbPlay6 = new javax.swing.JLabel();
        lbNext = new javax.swing.JLabel();
        lbRating = new javax.swing.JLabel();
        btRating = new javax.swing.JButton();
        RatingTf = new javax.swing.JTextField();
        btView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbSideBar.setBackground(new java.awt.Color(51, 51, 51));
        lbSideBar.setPreferredSize(new java.awt.Dimension(105, 768));

        homeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.home.empty.png"))); // NOI18N
        homeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLblMouseClicked(evt);
            }
        });

        newsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.newspaper.png"))); // NOI18N
        newsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsLblMouseClicked(evt);
            }
        });

        setLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.settings.png"))); // NOI18N
        setLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setLblMouseClicked(evt);
            }
        });

        fixLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.sport.football.png"))); // NOI18N
        fixLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fixLblMouseClicked(evt);
            }
        });

        mmLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.video.gallery.png"))); // NOI18N
        mmLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lbSideBarLayout = new javax.swing.GroupLayout(lbSideBar);
        lbSideBar.setLayout(lbSideBarLayout);
        lbSideBarLayout.setHorizontalGroup(
            lbSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbSideBarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(lbSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mmLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fixLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbSideBarLayout.setVerticalGroup(
            lbSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbSideBarLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(newsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(fixLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(mmLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(setLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout lbBodyLayout = new javax.swing.GroupLayout(lbBody);
        lbBody.setLayout(lbBodyLayout);
        lbBodyLayout.setHorizontalGroup(
            lbBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbBodyLayout.createSequentialGroup()
                .addComponent(lbSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        lbBodyLayout.setVerticalGroup(
            lbBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSideBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );

        lbBackGround.setBackground(new java.awt.Color(255, 255, 0));

        lbDisplay.setBackground(new java.awt.Color(255, 102, 102));
        lbDisplay.setPreferredSize(new java.awt.Dimension(201, 196));

        lbPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/videocameraclassic.png"))); // NOI18N
        lbPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlayMouseClicked(evt);
            }
        });

        lbWelcome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lbWelcome.setText("WELCOME TO BRAZIL");

        javax.swing.GroupLayout lbDisplayLayout = new javax.swing.GroupLayout(lbDisplay);
        lbDisplay.setLayout(lbDisplayLayout);
        lbDisplayLayout.setHorizontalGroup(
            lbDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplayLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(lbDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplayLayout.createSequentialGroup()
                        .addComponent(lbPlay)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplayLayout.createSequentialGroup()
                        .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        lbDisplayLayout.setVerticalGroup(
            lbDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPlay)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lbDisplay1.setBackground(new java.awt.Color(204, 153, 0));
        lbDisplay1.setPreferredSize(new java.awt.Dimension(201, 196));

        lbPlay2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/videocameraclassic.png"))); // NOI18N
        lbPlay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay2MouseClicked(evt);
            }
        });

        lbNeymar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbNeymar.setForeground(new java.awt.Color(255, 255, 255));
        lbNeymar.setText("Neymar NEXT Hope !!!");
        lbNeymar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNeymarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lbDisplay1Layout = new javax.swing.GroupLayout(lbDisplay1);
        lbDisplay1.setLayout(lbDisplay1Layout);
        lbDisplay1Layout.setHorizontalGroup(
            lbDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lbDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNeymar)
                    .addComponent(lbPlay2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        lbDisplay1Layout.setVerticalGroup(
            lbDisplay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNeymar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPlay2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        lbDisplay2.setBackground(new java.awt.Color(255, 0, 255));
        lbDisplay2.setPreferredSize(new java.awt.Dimension(201, 196));

        lbParty.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbParty.setForeground(new java.awt.Color(255, 255, 255));
        lbParty.setText("Don't Stop The Party");

        lbPlay3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/videocameraclassic.png"))); // NOI18N
        lbPlay3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lbDisplay2Layout = new javax.swing.GroupLayout(lbDisplay2);
        lbDisplay2.setLayout(lbDisplay2Layout);
        lbDisplay2Layout.setHorizontalGroup(
            lbDisplay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(lbDisplay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbDisplay2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbPlay3))
                    .addComponent(lbParty, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        lbDisplay2Layout.setVerticalGroup(
            lbDisplay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbParty, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlay3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbDisplay3.setBackground(new java.awt.Color(0, 204, 204));
        lbDisplay3.setMinimumSize(new java.awt.Dimension(201, 272));
        lbDisplay3.setPreferredSize(new java.awt.Dimension(201, 196));

        lbPlay4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/videocameraclassic.png"))); // NOI18N
        lbPlay4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay4MouseClicked(evt);
            }
        });

        lbWinner.setBackground(new java.awt.Color(255, 255, 255));
        lbWinner.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbWinner.setForeground(new java.awt.Color(255, 255, 255));
        lbWinner.setText("Two Teams One Winner");

        javax.swing.GroupLayout lbDisplay3Layout = new javax.swing.GroupLayout(lbDisplay3);
        lbDisplay3.setLayout(lbDisplay3Layout);
        lbDisplay3Layout.setHorizontalGroup(
            lbDisplay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(lbDisplay3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbPlay4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lbDisplay3Layout.setVerticalGroup(
            lbDisplay3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbWinner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlay4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbDisplay4.setBackground(new java.awt.Color(255, 153, 0));
        lbDisplay4.setPreferredSize(new java.awt.Dimension(201, 196));

        lbPlay5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/videocameraclassic.png"))); // NOI18N
        lbPlay5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay5MouseClicked(evt);
            }
        });

        lbSkills.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbSkills.setForeground(new java.awt.Color(255, 255, 255));
        lbSkills.setText("What a skills !!!");

        javax.swing.GroupLayout lbDisplay4Layout = new javax.swing.GroupLayout(lbDisplay4);
        lbDisplay4.setLayout(lbDisplay4Layout);
        lbDisplay4Layout.setHorizontalGroup(
            lbDisplay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay4Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(lbDisplay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay4Layout.createSequentialGroup()
                        .addComponent(lbPlay5)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay4Layout.createSequentialGroup()
                        .addComponent(lbSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        lbDisplay4Layout.setVerticalGroup(
            lbDisplay4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPlay5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbDisplay5.setBackground(new java.awt.Color(0, 153, 0));
        lbDisplay5.setForeground(new java.awt.Color(255, 255, 255));
        lbDisplay5.setPreferredSize(new java.awt.Dimension(201, 196));

        lbPlay6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/multimidia-icons/videocameraclassic.png"))); // NOI18N
        lbPlay6.setText("jLabel2");
        lbPlay6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlay6MouseClicked(evt);
            }
        });

        lbNext.setBackground(new java.awt.Color(255, 255, 255));
        lbNext.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbNext.setForeground(new java.awt.Color(255, 255, 255));
        lbNext.setText("Who is NEXT");

        javax.swing.GroupLayout lbDisplay5Layout = new javax.swing.GroupLayout(lbDisplay5);
        lbDisplay5.setLayout(lbDisplay5Layout);
        lbDisplay5Layout.setHorizontalGroup(
            lbDisplay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay5Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(lbDisplay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay5Layout.createSequentialGroup()
                        .addComponent(lbPlay6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbDisplay5Layout.createSequentialGroup()
                        .addComponent(lbNext, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        lbDisplay5Layout.setVerticalGroup(
            lbDisplay5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbDisplay5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNext, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPlay6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lbRating.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbRating.setForeground(new java.awt.Color(255, 0, 51));
        lbRating.setText("Rate This Week Videous ( 0-10)");

        btRating.setBackground(new java.awt.Color(51, 51, 255));
        btRating.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        btRating.setForeground(new java.awt.Color(255, 255, 255));
        btRating.setText("RATE");
        btRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRatingActionPerformed(evt);
            }
        });

        RatingTf.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        RatingTf.setAlignmentX(5.0F);
        RatingTf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RatingTf.setMargin(new java.awt.Insets(20, 20, 20, 20));

        btView.setBackground(new java.awt.Color(51, 51, 255));
        btView.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        btView.setForeground(new java.awt.Color(255, 255, 255));
        btView.setText("View Ratings");
        btView.setPreferredSize(new java.awt.Dimension(140, 70));
        btView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lbBackGroundLayout = new javax.swing.GroupLayout(lbBackGround);
        lbBackGround.setLayout(lbBackGroundLayout);
        lbBackGroundLayout.setHorizontalGroup(
            lbBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbBackGroundLayout.createSequentialGroup()
                .addGroup(lbBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lbBackGroundLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(lbBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbDisplay3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(lbBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(lbBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lbBackGroundLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btRating, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(RatingTf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btView, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbBackGroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbRating, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        lbBackGroundLayout.setVerticalGroup(
            lbBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbBackGroundLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(lbBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDisplay1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(lbDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(lbDisplay2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(lbBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(lbRating, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lbBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RatingTf, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRating, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1025, 804));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLblMouseClicked
       
       // this method is opening the particular GUI , and hides the previous , eg if you are in section "highlights" and you click on "top 10" section
       // it will open "top 10 " and will hide "highlights
        
        MasterMenu m = new MasterMenu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeLblMouseClicked

    private void newsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsLblMouseClicked
       
        NewsMenu myNews = new NewsMenu();
        myNews.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newsLblMouseClicked

    private void setLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setLblMouseClicked
       
        UserSettings u = new UserSettings();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_setLblMouseClicked

    private void fixLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fixLblMouseClicked
        
        FixGUITest myFix = null;
       try {
           myFix = new FixGUITest();
       } catch (IOException ex) {
           Logger.getLogger(MmVideousGUI.class.getName()).log(Level.SEVERE, null, ex);
       }
        myFix.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fixLblMouseClicked

    private void mmLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmLblMouseClicked
   
   // this method is opening the particular GUI , and hides the previous , eg if you are in section "highlights" and you click on "top 10" section
  // it will open "top 10 " and will hide "highlights  
        MmMultimediaGUI myMulti = new MmMultimediaGUI();
        myMulti.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mmLblMouseClicked

    private void lbPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayMouseClicked
       
    //This method is opening a file by using the defoult application eg "windows media player
    //  http://stackoverflow.com/questions/20440484/embed-a-youtube-video-to-jframe
    //this multimedia section is responsible to open and play videous,
            File welcome = new File("src/worldcupapp/Vid/The 2014 FIFA World Cup is coming!.mp4");
        try {
            Desktop.getDesktop().open(welcome);
        } catch (IOException e) {
        }
    
    }//GEN-LAST:event_lbPlayMouseClicked

    private void lbNeymarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNeymarMouseClicked

    }//GEN-LAST:event_lbNeymarMouseClicked

    private void lbPlay2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay2MouseClicked
        
             File neymar = new File("src/worldcupapp/Vid/Neymar - Brazilian Hope.mp4");
        try {
            Desktop.getDesktop().open(neymar);
        } catch (IOException c) {
        }
    }//GEN-LAST:event_lbPlay2MouseClicked

    private void lbPlay4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay4MouseClicked
        
              File match = new File("src/worldcupapp/Vid/most anticipated match.mp4");
        try {
            Desktop.getDesktop().open(match);
        } catch (IOException c) {
        }
        
    }//GEN-LAST:event_lbPlay4MouseClicked

    private void lbPlay5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay5MouseClicked
        
               File skills = new File("src/worldcupapp/Vid/Skills.mp4");
        try {
            Desktop.getDesktop().open(skills);
        } catch (IOException c) {
        }
        
    }//GEN-LAST:event_lbPlay5MouseClicked

    private void lbPlay6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay6MouseClicked
       
               File trailer = new File("src/worldcupapp/Vid/Trailer.mp4");
        try {
            Desktop.getDesktop().open(trailer);
        } catch (IOException c) {
        }
    }//GEN-LAST:event_lbPlay6MouseClicked

    private void lbPlay3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlay3MouseClicked
   
                File party = new File("src/worldcupapp/Vid/party.mp4");
        try {
            Desktop.getDesktop().open(party);
        } catch (IOException c) {
        }
        
    }//GEN-LAST:event_lbPlay3MouseClicked

    private void btRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRatingActionPerformed
        
        // Get text from TextFields
        rate = Integer.parseInt(RatingTf.getText());
        
         //create a new rate object
        
        MmVideous m = new MmVideous();
        
        //add contents of textfields to m
        m.SetRate(rate);
        
        //add m to array of Rate objects
        rList.add(m);
        
        //increase count to show that another object has been added to the array
        count++;
        
        //Creates file with all ratings
        
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String rate = RatingTf.getText();
        try {
            outFile = new File("ratings.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(rate);
            bw.newLine();

            bw.close();
            JOptionPane.showMessageDialog(null, "Thank you for rate our video");
        } catch (IOException e) {
            System.out.println("Error writing to file: " + e);
        }
    }//GEN-LAST:event_btRatingActionPerformed

    private void btViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewActionPerformed
     
       // Loop through array of objects 
        
       for(int i = 0 ; i<rList.size(); i++){
            MmVideous rate = new MmVideous();
            JOptionPane.showMessageDialog(null, "Your Rate  " +rList.get(i).getRate());
        }
        
        String Allrate;  
        String rate;
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("ratings.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);
            Allrate=("");

            rate = br.readLine();
            
            while (rate != null) {
                Allrate = Allrate+rate+",";  
                rate = br.readLine();
            }
            
            JOptionPane.showMessageDialog(null, "All Rates: "  + Allrate );
            br.close();
            
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmMultimediaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MmMultimediaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RatingTf;
    private javax.swing.JButton btRating;
    private javax.swing.JButton btView;
    private javax.swing.JLabel fixLbl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JPanel lbBackGround;
    private javax.swing.JPanel lbBody;
    private javax.swing.JPanel lbDisplay;
    private javax.swing.JPanel lbDisplay1;
    private javax.swing.JPanel lbDisplay2;
    private javax.swing.JPanel lbDisplay3;
    private javax.swing.JPanel lbDisplay4;
    private javax.swing.JPanel lbDisplay5;
    private javax.swing.JLabel lbNext;
    private javax.swing.JLabel lbNeymar;
    private javax.swing.JLabel lbParty;
    private javax.swing.JLabel lbPlay;
    private javax.swing.JLabel lbPlay2;
    private javax.swing.JLabel lbPlay3;
    private javax.swing.JLabel lbPlay4;
    private javax.swing.JLabel lbPlay5;
    private javax.swing.JLabel lbPlay6;
    private javax.swing.JLabel lbRating;
    private javax.swing.JPanel lbSideBar;
    private javax.swing.JLabel lbSkills;
    private javax.swing.JLabel lbWelcome;
    private javax.swing.JLabel lbWinner;
    private javax.swing.JLabel mmLbl;
    private javax.swing.JLabel newsLbl;
    private javax.swing.JLabel setLbl;
    // End of variables declaration//GEN-END:variables
}
