package worldcupapp;

/*
 * NewAdd.java
 * Version 2014-04-13
 * Date 13th April 2014
 * @author Nilsson Denver 13114492
 * @reference: Benny, Classrrom Assistant, How to set up an ArrayList to be accessed from other classes
 */
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class NewsAdd extends javax.swing.JFrame {

    /**
     * Creates new form NewsAdd
     */
    int articlenbr;
    String newstypeNews;
    String headlinetext;
    String fullarticletext;
    String imagesmall;
    String imagelarge;
    String newstypeTeam;
    String newstypePlayer;
    String newstypeOther;
    int count = 0;
// @reference: Benny, Classrrom Assistant, How to set up an ArrayList to be accessed from other classes
    public static ArrayList<NewsOther> NewsArrList;

    public NewsAdd() {
        initComponents();
        NewsArrList = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TfArticlenbr = new javax.swing.JTextField();
        LblArticlenbr = new javax.swing.JLabel();
        LblNewstype1 = new javax.swing.JLabel();
        lblNewstype2 = new javax.swing.JLabel();
        LblNewstype3 = new javax.swing.JLabel();
        LblNewstype4 = new javax.swing.JLabel();
        LblHeadlinetext = new javax.swing.JLabel();
        LblFullarticletext = new javax.swing.JLabel();
        LblImagesmall = new javax.swing.JLabel();
        TfNewstype1 = new javax.swing.JTextField();
        TfNewstype2 = new javax.swing.JTextField();
        TfNewstype3 = new javax.swing.JTextField();
        TfNewstype4 = new javax.swing.JTextField();
        TfHeadlinetext = new javax.swing.JTextField();
        TfImagesmall = new javax.swing.JTextField();
        LblImagelarge = new javax.swing.JLabel();
        TfImagelarge = new javax.swing.JTextField();
        SpFullarticletext = new javax.swing.JScrollPane();
        TaFullarticletext = new javax.swing.JTextArea();
        BtnUpdate = new javax.swing.JButton();
        BtnDisplay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TfArticlenbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfArticlenbrActionPerformed(evt);
            }
        });

        LblArticlenbr.setText("Articlenbr");

        LblNewstype1.setText("Newstype1");

        lblNewstype2.setText("Newstype2");

        LblNewstype3.setText("Newstype3");

        LblNewstype4.setText("Newstype4");

        LblHeadlinetext.setText("Headlinetext");

        LblFullarticletext.setText("Fullarticletext");

        LblImagesmall.setText("Imagesmall");

        TfNewstype1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNewstype1ActionPerformed(evt);
            }
        });

        LblImagelarge.setText("Imagelarge");

        TaFullarticletext.setColumns(20);
        TaFullarticletext.setRows(5);
        SpFullarticletext.setViewportView(TaFullarticletext);

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDisplay.setText("Display");
        BtnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDisplayActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Press Update and then Press Display to get the Data to load.\nThis is a temporary measure before FILE IO code is written!");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblNewstype1)
                            .addComponent(lblNewstype2)
                            .addComponent(LblNewstype3)
                            .addComponent(LblNewstype4)
                            .addComponent(LblHeadlinetext)
                            .addComponent(LblFullarticletext)
                            .addComponent(LblArticlenbr))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SpFullarticletext, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                                .addComponent(TfHeadlinetext))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TfNewstype4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(TfNewstype3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfNewstype2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfNewstype1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TfArticlenbr, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblImagelarge)
                                    .addComponent(LblImagesmall))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TfImagesmall)
                                    .addComponent(TfImagelarge, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(BtnUpdate)
                                        .addGap(106, 106, 106)
                                        .addComponent(BtnDisplay)
                                        .addGap(205, 205, 205)
                                        .addComponent(btnSave)
                                        .addGap(78, 78, 78)
                                        .addComponent(btnLoad)))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfArticlenbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblArticlenbr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNewstype1)
                    .addComponent(TfNewstype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewstype2)
                    .addComponent(TfNewstype2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNewstype3)
                    .addComponent(TfNewstype3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNewstype4)
                    .addComponent(TfNewstype4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblHeadlinetext)
                    .addComponent(TfHeadlinetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblFullarticletext)
                    .addComponent(SpFullarticletext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblImagesmall)
                    .addComponent(TfImagesmall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblImagelarge)
                    .addComponent(TfImagelarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnDisplay)
                    .addComponent(btnSave)
                    .addComponent(btnLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfNewstype1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNewstype1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNewstype1ActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
            NewsOther news;
            news = new NewsOther(articlenbr, newstypeNews, headlinetext, fullarticletext, imagesmall, imagelarge, newstypeTeam, newstypePlayer, newstypeOther);

articlenbr = Integer.parseInt(TfArticlenbr.getText());
newstypeNews = TfNewstype1.getText();
headlinetext = TfHeadlinetext.getText();
fullarticletext = TaFullarticletext.getText();
imagesmall = TfImagesmall.getText();
imagelarge = TfImagelarge.getText();
newstypeTeam = TfNewstype2.getText();
newstypePlayer = TfNewstype3.getText();
newstypeOther = TfNewstype4.getText();

            news.setArticlenbr(articlenbr);
            news.setNewstypeNews(newstypeNews);
            news.setNewstypeTeam(newstypeTeam);
            news.setNewstypePlayer(newstypePlayer);
            news.setNewstypeOther(newstypeOther);
            news.setHeadlinetext(headlinetext);
            news.setFullarticletext(fullarticletext);
            news.setImagesmall(imagesmall);
            news.setImagelarge(imagelarge);

            NewsArrList.add(news);

        

// TODO add your handling code here:
//        int k = 0;
//
//        //Automated for Testing without File IO options
//
//        for (k = 1; k <= 4; k = k + 1) { // k+0 is the number of articles preloaded
//            NewsOther news;
//            news = new NewsOther(articlenbr, newstypeNews, headlinetext, fullarticletext, imagesmall, imagelarge, newstypeTeam, newstypePlayer, newstypeOther);
//
//            news.setArticlenbr(1000 + k);
//            news.setNewstypeNews("n");
//            news.setNewstypeTeam("tt");
//            news.setNewstypePlayer("x");
//            news.setNewstypeOther("x");
//            news.setHeadlinetext("Headline Text " + k);
//            news.setFullarticletext("Full Article Text lots of text. and a second sentence " + k);
//            news.setImagesmall((1000 + k) + ".jpg");
//            news.setImagelarge((1000 + k) + "t.png");
//
//            NewsArrList.add(news);
//        }
//        for (k = 5; k <= 8; k = k + 1) { // k+0 is the number of articles preloaded
//            NewsOther news;
//            news = new NewsOther(articlenbr, newstypeNews, headlinetext, fullarticletext, imagesmall, imagelarge, newstypeTeam, newstypePlayer, newstypeOther);
//
//            news.setArticlenbr(1000 + k);
//            news.setNewstypeNews("n");
//            news.setNewstypeTeam("tt");
//            news.setNewstypePlayer("pp");
//            news.setNewstypeOther("x");
//            news.setHeadlinetext("Headline Text " + k);
//            news.setFullarticletext("Full Article Text lots of text. and a second sentence " + k);
//            news.setImagesmall((1000 + k) + ".jpg");
//            news.setImagelarge((3000 + k) + "p.png");
//
//            NewsArrList.add(news);
//        }
//        for (k = 9; k <= 12; k = k + 1) { // k+0 is the number of articles preloaded
//            NewsOther news;
//            news = new NewsOther(articlenbr, newstypeNews, headlinetext, fullarticletext, imagesmall, imagelarge, newstypeTeam, newstypePlayer, newstypeOther);
//
//            news.setArticlenbr(1000 + k);
//            news.setNewstypeNews("n");
//            news.setNewstypeTeam("x");
//            news.setNewstypePlayer("x");
//            news.setNewstypeOther("oo");
//            news.setHeadlinetext("Headline Text " + k);
//            news.setFullarticletext("Full Article Text lots of text. and a second sentence " + k);
//            news.setImagesmall((1000 + k) + ".jpg");
//            news.setImagelarge((1000 + k) + ".png");
//
//            NewsArrList.add(news);
//        }
//        //JOptionPane.showMessageDialog(null, "calc " + (1000 + k) + ".jpg");
//        JOptionPane.showMessageDialog(null, "Data has been updated - Press Display to see the data in the App");
        
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDisplayActionPerformed
        // TODO add your handling code here:
          for(int i=0; i< NewsArrList.size(); i++){
          JOptionPane.showMessageDialog(null,"1 = "+NewsArrList.size()+" "+NewsArrList.get(i).getArticlenbr());
        }
        NewsMenu myNewsMenu = new NewsMenu();
        myNewsMenu.setVisible(true);
    }//GEN-LAST:event_BtnDisplayActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
          //Declare objects required to write object to a file
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        //Use a try statement
        try {
            //create objects  
            outFile = new File("news.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            //write objects to file
            oStream.writeObject(NewsArrList);

            JOptionPane.showMessageDialog(null, "File written successfully");
            //close stream
            oStream.close();
        } //catch the IOException  
        catch (IOException e) {
            System.out.println(e);
        }
      // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // Declare objects required to read from file
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        //use a try statement
        
        try {
        //create objects
            inFile = new File ("news.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
        //read arrayList from file
            
            NewsArrList = (ArrayList<NewsOther>)oStream.readObject();
//loop through the ArrayList
            //for (int i = 0; i<qList.size(); i =i+1){
//            for(NewsOther x:NewsArrList){
        //Print the contents of each object
//                JOptionPane.showMessageDialog(null,"Item 1 "+x.getArticlenbr());
//            }        
                  
        //close the stream
            
        oStream.close();
        }
        //catch IOException
         catch (IOException e) {
                System.out.println(e);
            }           
        //catch classNotFoundException
        catch(ClassNotFoundException ex){
	System.out.println(ex);
        }

    }//GEN-LAST:event_btnLoadActionPerformed

    private void TfArticlenbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfArticlenbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfArticlenbrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewsAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewsAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewsAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewsAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewsAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDisplay;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JLabel LblArticlenbr;
    private javax.swing.JLabel LblFullarticletext;
    private javax.swing.JLabel LblHeadlinetext;
    private javax.swing.JLabel LblImagelarge;
    private javax.swing.JLabel LblImagesmall;
    private javax.swing.JLabel LblNewstype1;
    private javax.swing.JLabel LblNewstype3;
    private javax.swing.JLabel LblNewstype4;
    private javax.swing.JScrollPane SpFullarticletext;
    private javax.swing.JTextArea TaFullarticletext;
    private javax.swing.JTextField TfArticlenbr;
    private javax.swing.JTextField TfHeadlinetext;
    private javax.swing.JTextField TfImagelarge;
    private javax.swing.JTextField TfImagesmall;
    private javax.swing.JTextField TfNewstype1;
    private javax.swing.JTextField TfNewstype2;
    private javax.swing.JTextField TfNewstype3;
    private javax.swing.JTextField TfNewstype4;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblNewstype2;
    // End of variables declaration//GEN-END:variables
}
