package worldcupapp;

/*
 * NewsTeamGUI.java
 * Version 2014-04-16
 * Date 16th April 2014
 * @author Nilsson Denver 13114492
 * @reference: http://stackoverflow.com/questions/4801386/how-do-i-add-an-image-to-a-jbutton 
 */
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class NewsTeamGUI extends javax.swing.JFrame {

    private String displayText;
    private String imgname;
    /**
     * Creates new form NewsTeamGUI
     */
    ArrayList<NewsTeam> newsArrListTeam;
    protected int countTeam = 0;

    public NewsTeamGUI() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 0));
        if (NewsAdd.NewsArrList != null) {
            if (NewsAdd.NewsArrList.size() > 0) {

                newsArrListTeam = new ArrayList<>();
                // ** Array List ** - This take the Full News file and puts it into an arraylist containing
                //  only Team News. Team News is identified by the "tt" in the data
                for (int j = 0; j < NewsAdd.NewsArrList.size(); j = j + 1) {
                    if (NewsAdd.NewsArrList.get(j).getNewstypeTeam().equalsIgnoreCase("tt")) {
                        newsArrListTeam.add(NewsAdd.NewsArrList.get(j));

                    }
                    //else{
                    //JOptionPane.showMessageDialog(null,"error ");
                    //}
                }
                newsArea.setText(newsArrListTeam.get(0).getHeadlinetext() + "\n\n" + newsArrListTeam.get(0).getFullarticletext());
                //
                try {
                    Image img;
                    //JOptionPane.showMessageDialog(null, "countPlayer "+countPlayer);
                    //JOptionPane.showMessageDialog(null, "News Arr List image large " + newsArrListTeam.get(countPlayer).getImagelarge());
                    img = ImageIO.read(getClass().getResource("/worldcupapp/news_images/" + newsArrListTeam.get(0).getImagelarge()));
                    newsBtnUpdates.setIcon(new ImageIcon(img));
                    //newsBtnUpdates.setText(newsArrListTeam.get(0).getImagelarge());
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "error ");
                }
                //

                //newsBtnUpdates.setText(newsArrListTeam.get(0).getImagelarge());
            }
        }
    }

    //this method closes the previous JPanel and opens a new JPanel
    //found at http://www.youtube.com/watch?v=Q2itkhLHaeE
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newsBtnUpdates = new javax.swing.JButton();
        newsArea = new java.awt.TextArea();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        sidebar = new javax.swing.JPanel();
        homeLbl = new javax.swing.JLabel();
        newsLbl = new javax.swing.JLabel();
        setLbl = new javax.swing.JLabel();
        fixLbl = new javax.swing.JLabel();
        mmLbl = new javax.swing.JLabel();
        fontSizeButton = new javax.swing.JButton();
        fontSizeSlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Team News");
        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(255, 255, 204));
        setResizable(false);

        newsBtnUpdates.setBackground(new java.awt.Color(255, 255, 204));
        newsBtnUpdates.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        newsBtnUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsBtnUpdatesActionPerformed(evt);
            }
        });

        newsArea.setBackground(new java.awt.Color(255, 255, 204));
        newsArea.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btnPrevious.setBackground(new java.awt.Color(153, 255, 153));
        btnPrevious.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(153, 255, 153));
        btnNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        sidebar.setBackground(new java.awt.Color(51, 51, 51));
        sidebar.setPreferredSize(new java.awt.Dimension(105, 768));

        homeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.home.empty.png"))); // NOI18N
        homeLbl.setToolTipText("Home");
        homeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLblMouseClicked(evt);
            }
        });

        newsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.newspaper.png"))); // NOI18N
        newsLbl.setToolTipText("News");
        newsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsLblMouseClicked(evt);
            }
        });

        setLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.settings.png"))); // NOI18N
        setLbl.setToolTipText("Settings");
        setLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setLblMouseClicked(evt);
            }
        });

        fixLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.sport.football.png"))); // NOI18N
        fixLbl.setToolTipText("News");
        fixLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fixLblMouseClicked(evt);
            }
        });

        mmLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.video.gallery.png"))); // NOI18N
        mmLbl.setToolTipText("MultiMedia");
        mmLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mmLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fixLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(newsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(fixLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(mmLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(setLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fontSizeButton.setText("Click here to change reading size of font");
        fontSizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontSizeButtonActionPerformed(evt);
            }
        });

        fontSizeSlider.setMajorTickSpacing(2);
        fontSizeSlider.setMaximum(24);
        fontSizeSlider.setMinimum(8);
        fontSizeSlider.setMinorTickSpacing(1);
        fontSizeSlider.setPaintLabels(true);
        fontSizeSlider.setPaintTicks(true);
        fontSizeSlider.setSnapToTicks(true);
        fontSizeSlider.setToolTipText("Choose Font Size ");
        fontSizeSlider.setValue(14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fontSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fontSizeButton))
                            .addComponent(newsArea, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addComponent(newsBtnUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrevious)
                            .addComponent(btnNext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newsArea, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newsBtnUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fontSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fontSizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        setSize(new java.awt.Dimension(1042, 815));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        countTeam = countTeam - 1;
        if (countTeam < 0) {
            countTeam = -1 + newsArrListTeam.size();
        }
        newsArea.setText(newsArrListTeam.get(countTeam).getHeadlinetext() + "\n\n" + newsArrListTeam.get(countTeam).getFullarticletext());
// @reference: http://stackoverflow.com/questions/4801386/how-do-i-add-an-image-to-a-jbutton
        try {
            Image img;
            //JOptionPane.showMessageDialog(null, "countTeam " + countTeam);
            //JOptionPane.showMessageDialog(null, "News Arr List image large " + newsArrListTeam.get(countTeam).getImagelarge());
            img = ImageIO.read(getClass().getResource("/worldcupapp/news_images/" + newsArrListTeam.get(countTeam).getImagelarge()));
            newsBtnUpdates.setIcon(new ImageIcon(img));
            //newsBtnUpdates.setText(newsArrListTeam.get(countTeam).getImagelarge());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "error ");
        }

        //JOptionPane.showMessageDialog(null, "Count is " + countTeam + " imgname " + imgname);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        countTeam = countTeam + 1;
        if (countTeam >= newsArrListTeam.size()) {
            countTeam = 0;
        }

        newsArea.setText(newsArrListTeam.get(countTeam).getHeadlinetext() + "\n\n" + newsArrListTeam.get(countTeam).getFullarticletext());
// @reference: http://stackoverflow.com/questions/4801386/how-do-i-add-an-image-to-a-jbutton        
        try {
            Image img;
            //JOptionPane.showMessageDialog(null, "countTeam " + countTeam);
            //JOptionPane.showMessageDialog(null, "News Arr List image large " + newsArrListTeam.get(countTeam).getImagelarge());
            img = ImageIO.read(getClass().getResource("/worldcupapp/news_images/" + newsArrListTeam.get(countTeam).getImagelarge()));
            newsBtnUpdates.setIcon(new ImageIcon(img));
            //newsBtnUpdates.setText(newsArrListTeam.get(countTeam).getImagelarge());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "error ");
        }

        //JOptionPane.showMessageDialog(null, "Count is " + countTeam + " imgname " + imgname);
    }//GEN-LAST:event_btnNextActionPerformed

    private void newsBtnUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsBtnUpdatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsBtnUpdatesActionPerformed

    private void homeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLblMouseClicked
        // this method is opening the particular GUI , and hides the previous , eg if you are in section "highlights" and you click on "top 10" section
        // it will open "top 10 " and will hide "highlights

        MasterMenu m = new MasterMenu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeLblMouseClicked

    private void newsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsLblMouseClicked

        NewsMenu myNews = new NewsMenu();
        myNews.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newsLblMouseClicked

    private void setLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setLblMouseClicked

        UserSettings u = new UserSettings();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_setLblMouseClicked

    private void fixLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fixLblMouseClicked

        FixGUITest myFix = null;
        try {
            myFix = new FixGUITest();
        } catch (IOException ex) {
            Logger.getLogger(MmMultimediaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        myFix.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fixLblMouseClicked

    private void mmLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmLblMouseClicked

        // this method is opening the particular GUI , and hides the previous , eg if you are in section "highlights" and you click on "top 10" sectio
        // it will open "top 10 " and will hide "highlights
        MmMultimediaGUI myMulti = new MmMultimediaGUI();
        myMulti.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mmLblMouseClicked

    private void fontSizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontSizeButtonActionPerformed
        int fontsize;
        fontsize = fontSizeSlider.getValue();
        newsArea.setFont(new java.awt.Font("Calibri", 0, fontsize));
    }//GEN-LAST:event_fontSizeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel fixLbl;
    private javax.swing.JButton fontSizeButton;
    private javax.swing.JSlider fontSizeSlider;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel mmLbl;
    private java.awt.TextArea newsArea;
    private javax.swing.JButton newsBtnUpdates;
    private javax.swing.JLabel newsLbl;
    private javax.swing.JLabel setLbl;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
