package worldcupapp;

/*
 * NewGUI.java
 * Version 2014-04-16
 * Date 16th April 2014
 * @author Nilsson Denver 13114492
 * @reference http://www.youtube.com/watch?v=Q2itkhLHaeE
 * @reference: http://stackoverflow.com/questions/4801386/how-do-i-add-an-image-to-a-jbutton 
 * JSlider was researched and not copied from anothe website. Used a button to update font size as could not get it to automate!
 */
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import static worldcupapp.NewsAdd.NewsArrList;

public class NewsGUI extends javax.swing.JFrame {

    private String displayText;

    /**
     * Creates new form NewsMenuGUI2
     */
    public NewsGUI() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 0));
//Start of Loading the data file        
        // Declare objects required to read from file
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        //use a try statement

        try {
            //create objects
            inFile = new File("news.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            //read arrayList from file

            NewsArrList = (ArrayList<NewsOther>) oStream.readObject();
//loop through the ArrayList
            //for (int i = 0; i<qList.size(); i =i+1){
//            for(NewsOther x:NewsArrList){
            //Print the contents of each object
//                JOptionPane.showMessageDialog(null,"Item 1 "+x.getArticlenbr());
//            }        

            //close the stream
            oStream.close();
        } //catch IOException
        catch (IOException e) {
            System.out.println(e);
        } //catch classNotFoundException
        catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }

//End of Data File Loading
        if (NewsAdd.NewsArrList != null) {
            if (NewsAdd.NewsArrList.size() > 0) {
                newsBtn1.setText(NewsAdd.NewsArrList.get(0).headlinetext);
                newsBtn2.setText(NewsAdd.NewsArrList.get(1).headlinetext);
                newsBtn3.setText(NewsAdd.NewsArrList.get(2).headlinetext);
            }
        }
    }

    //reference: this method closes the previous JPanel and opens a new JPanel
    //found at http://www.youtube.com/watch?v=Q2itkhLHaeE
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newsBtn1 = new javax.swing.JButton();
        newsBtn3 = new javax.swing.JButton();
        newsBtn2 = new javax.swing.JButton();
        newsBtnUpdates = new javax.swing.JButton();
        newsArea = new java.awt.TextArea();
        btnInfo = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        homeLbl = new javax.swing.JLabel();
        newsLbl = new javax.swing.JLabel();
        setLbl = new javax.swing.JLabel();
        fixLbl = new javax.swing.JLabel();
        mmLbl = new javax.swing.JLabel();
        fontSizeSlider = new javax.swing.JSlider();
        fontSizeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("The News");
        setBackground(new java.awt.Color(255, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 204, 204));
        setResizable(false);

        newsBtn1.setBackground(new java.awt.Color(255, 255, 204));
        newsBtn1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        newsBtn1.setText("news 1 text here");
        newsBtn1.setAutoscrolls(true);
        newsBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newsBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsBtn1MouseClicked(evt);
            }
        });
        newsBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsBtn1ActionPerformed(evt);
            }
        });

        newsBtn3.setBackground(new java.awt.Color(255, 255, 204));
        newsBtn3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        newsBtn3.setText("news 3 text here - long long long long");
        newsBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsBtn3MouseClicked(evt);
            }
        });
        newsBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsBtn3ActionPerformed(evt);
            }
        });

        newsBtn2.setBackground(new java.awt.Color(255, 255, 204));
        newsBtn2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        newsBtn2.setText("news 2 text here - medi medi");
        newsBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsBtn2MouseClicked(evt);
            }
        });
        newsBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsBtn2ActionPerformed(evt);
            }
        });

        newsBtnUpdates.setBackground(new java.awt.Color(255, 255, 204));
        newsBtnUpdates.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        newsBtnUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsBtnUpdatesActionPerformed(evt);
            }
        });

        newsArea.setBackground(new java.awt.Color(255, 255, 204));
        newsArea.setEditable(false);
        newsArea.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btnInfo.setBackground(new java.awt.Color(255, 255, 204));

        sidebar.setBackground(new java.awt.Color(51, 51, 51));
        sidebar.setPreferredSize(new java.awt.Dimension(105, 768));

        homeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.home.empty.png"))); // NOI18N
        homeLbl.setToolTipText("Home");
        homeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLblMouseClicked(evt);
            }
        });

        newsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.newspaper.png"))); // NOI18N
        newsLbl.setToolTipText("News");
        newsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newsLblMouseClicked(evt);
            }
        });

        setLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.settings.png"))); // NOI18N
        setLbl.setToolTipText("Settings");
        setLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setLblMouseClicked(evt);
            }
        });

        fixLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.sport.football.png"))); // NOI18N
        fixLbl.setToolTipText("Fixtures");
        fixLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fixLblMouseClicked(evt);
            }
        });

        mmLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldcupapp/sidebar_icons/appbar.video.gallery.png"))); // NOI18N
        mmLbl.setToolTipText("MultiMedia");
        mmLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mmLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fixLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(newsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(fixLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(mmLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(setLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fontSizeSlider.setBackground(new java.awt.Color(255, 255, 204));
        fontSizeSlider.setMajorTickSpacing(2);
        fontSizeSlider.setMaximum(24);
        fontSizeSlider.setMinimum(8);
        fontSizeSlider.setMinorTickSpacing(1);
        fontSizeSlider.setPaintLabels(true);
        fontSizeSlider.setPaintTicks(true);
        fontSizeSlider.setSnapToTicks(true);
        fontSizeSlider.setToolTipText("CHoose Font Size");
        fontSizeSlider.setValue(14);

        fontSizeButton.setBackground(new java.awt.Color(255, 255, 204));
        fontSizeButton.setText("Click here to change reading size of font");
        fontSizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontSizeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fontSizeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(fontSizeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newsBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newsBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newsBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(newsArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newsBtnUpdates, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(btnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newsBtnUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newsBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newsBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newsBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(newsArea, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fontSizeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fontSizeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1042, 815));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newsBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsBtn3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newsBtn3MouseClicked

    private void newsBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsBtn1MouseClicked
                // TODO add your handling code here:


    }//GEN-LAST:event_newsBtn1MouseClicked

    private void newsBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsBtn1ActionPerformed
        // TODO add your handling code here:
        displayText = newsBtn1.getText();
        newsArea.setText(NewsAdd.NewsArrList.get(0).headlinetext + "\n\n" + NewsAdd.NewsArrList.get(0).fullarticletext);

// reference: http://stackoverflow.com/questions/4801386/how-do-i-add-an-image-to-a-jbutton
        try {
            Image img;
            img = ImageIO.read(getClass().getResource("news_images/1001t.png"));
            newsBtnUpdates.setIcon(new ImageIcon(img));
            newsBtnUpdates.setText("");
            newsBtn1.setText("");
            newsBtn2.setText(NewsAdd.NewsArrList.get(1).headlinetext);
            newsBtn3.setText(NewsAdd.NewsArrList.get(2).headlinetext);
            newsBtn1.setIcon(new ImageIcon(img));
            newsBtn2.setIcon(null);
            newsBtn3.setIcon(null);
        } catch (IOException ex) {

        }

    }//GEN-LAST:event_newsBtn1ActionPerformed

    private void newsBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsBtn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newsBtn2MouseClicked

    private void newsBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsBtn2ActionPerformed
        // TODO add your handling code here:
        displayText = newsBtn2.getText();
        newsArea.setText(NewsAdd.NewsArrList.get(1).headlinetext + "\n\n" + NewsAdd.NewsArrList.get(1).fullarticletext);
// reference: http://stackoverflow.com/questions/4801386/how-do-i-add-an-image-to-a-jbutton
        try {
            Image img;
            img = ImageIO.read(getClass().getResource("news_images/1002p.png"));
            // (This part by Nilsson Denver) keeps only current news article active, closes all other news stories and resources    
            newsBtnUpdates.setIcon(new ImageIcon(img));
            newsBtnUpdates.setText("");
            newsBtn1.setText(NewsAdd.NewsArrList.get(0).headlinetext);
            newsBtn2.setText(" ");
            newsBtn3.setText(NewsAdd.NewsArrList.get(2).headlinetext);
            newsBtn1.setIcon(null);
            newsBtn2.setIcon(new ImageIcon(img));
            newsBtn3.setIcon(null);
        } catch (IOException ex) {

        }
    }//GEN-LAST:event_newsBtn2ActionPerformed

    private void newsBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsBtn3ActionPerformed
        // TODO add your handling code here:
        displayText = newsBtn3.getText();
        newsArea.setText(NewsAdd.NewsArrList.get(2).headlinetext + "\n\n" + NewsAdd.NewsArrList.get(2).fullarticletext);
// reference: http://stackoverflow.com/questions/4801386/how-do-i-add-an-image-to-a-jbutton
        try {
            Image img;
            img = ImageIO.read(getClass().getResource("news_images/1003t.png"));
            newsBtnUpdates.setIcon(new ImageIcon(img));
            newsBtnUpdates.setText("");
            newsBtn1.setText(NewsAdd.NewsArrList.get(0).headlinetext);
            newsBtn2.setText(NewsAdd.NewsArrList.get(1).headlinetext);
            newsBtn3.setText(" ");
            newsBtn1.setIcon(null);
            newsBtn2.setIcon(null);
            newsBtn3.setIcon(new ImageIcon(img));
        } catch (IOException ex) {

        }
    }//GEN-LAST:event_newsBtn3ActionPerformed

    private void newsBtnUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsBtnUpdatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newsBtnUpdatesActionPerformed

    private void homeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLblMouseClicked
        // this method is opening the particular GUI , and hides the previous , eg if you are in section "highlights" and you click on "top 10" section
        // it will open "top 10 " and will hide "highlights

        MasterMenu m = new MasterMenu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeLblMouseClicked

    private void newsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsLblMouseClicked

        NewsMenu myNews = new NewsMenu();
        myNews.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newsLblMouseClicked

    private void setLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setLblMouseClicked

        UserSettings u = new UserSettings();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_setLblMouseClicked

    private void fixLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fixLblMouseClicked

        FixGUITest myFix = null;
        try {
            myFix = new FixGUITest();
        } catch (IOException ex) {
            Logger.getLogger(MmMultimediaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        myFix.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_fixLblMouseClicked

    private void mmLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmLblMouseClicked

        // this method is opening the particular GUI , and hides the previous , eg if you are in section "highlights" and you click on "top 10" sectio
        // it will open "top 10 " and will hide "highlights
        MmMultimediaGUI myMulti = new MmMultimediaGUI();
        myMulti.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mmLblMouseClicked

    private void fontSizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontSizeButtonActionPerformed
        // TODO add your handling code here:
        int fontsize = fontSizeSlider.getValue();
        newsArea.setFont(new java.awt.Font("Calibri", 0, fontsize));


    }//GEN-LAST:event_fontSizeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnInfo;
    private javax.swing.JLabel fixLbl;
    private javax.swing.JButton fontSizeButton;
    private javax.swing.JSlider fontSizeSlider;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel mmLbl;
    private java.awt.TextArea newsArea;
    public javax.swing.JButton newsBtn1;
    public javax.swing.JButton newsBtn2;
    public javax.swing.JButton newsBtn3;
    private javax.swing.JButton newsBtnUpdates;
    private javax.swing.JLabel newsLbl;
    private javax.swing.JLabel setLbl;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
